layout.tt, news.xml, nixos/community.tt
This fixes more https warnings for mixed content on the homepage. Fixes all mentioned in #21, so closes #21.
=> fix more https warnings

css/nixos-site.css, layout.tt
This helps with the naviation and discoverability of the various projects.
Right now the user has to either follow the links or enter the right path in
the URL to navigate between these.
This tries to fix one of the complaint @garbas had during the talk.
=> Restore the project menu

css/nixos-site.css
Remove `text-align: justify` from paragraphs as it adds little and can harm readability significantly.
I'd argue it should never be used, but I only noticed it in the paragraph tag.
Before:
After:
=> Remove justified alignment from p tags

nix/install.in
[Copied from #62, since the underlying repo for the PR went away]
This PR should make the default installation method a little bit more robust:
curl https://nixos.org/nix/install | sh
As it is, after a failed attempt to run the above (e.g. due to a keyboard interrupt or failed partial download) the second invocation of the same command will also fail because the nix-binary-tarball-unpack directory won't have been cleaned up and the attempt to mkdir it at the same location will error out.
This PR uses mktemp (in a way that should work at least on OS X and Linux) and an exit trap to fix this.
=> install.in: mktemp -d and reliably cleanup tarball dir on exit

nix/install.in
In the Nix installation script at `nix/install.in`, replace a Bash-ism
with its POSIX-compatible equivalent, and fix some (minor) quoting
issues found by ShellCheck.
Credit to @wycats for hitting the Bash-ism, and thereby prompting me to
fix it.
NOTE: This will require the PGP signature at `nix/install.sig` to be
updated, which I don't believe I can do.
=> Nix install script: Fix Bash-ism, quoting issues

nix/download.tt
the current install directions are incorrect:
$ wget http://localhost/nix/install wget http://localhost/nix/install.sig
=> Correct URLs for wget on installer

nix/download.tt
Point to distracted readers that the script outputs further instructions.
Alternatively, we could duplicate those instructions here if they're stable enough. That seems plausible, but I'm too new to Nix to be sure. OTOH, I'm not sure the current uninstall instructions are accurate (see #99).
=> Point out install script outputs instructions

nixos/options.tt
(partial) fix for issue #89
- option description is now fully displayed and now longer truncated
- links are still not rendered as HTML links
=> (partial) fix for #89

Makefile, layout.tt, nixos/security.tt
I think we can close https://github.com/NixOS/nixpkgs/issues/13515 after merging this. The list of members isn't intended to be final.
=> Add a Security page for NixOS

nix/download.tt
Rather than switching between curl and wget, stick with the same command.
=> Use curl for both download examples

news.xml
There are currently two "fourth stable release branch" of NixOS.
Unless I didn't get something, this commit should fix the numbering on the announcement page.
=> Fix numbering of NixOS releases on news page

Makefile, news.xml, nixos/about.tt, nixos/download.tt
As soon as https://hydra.nixos.org/build/51054560 passes, we have a stable 17.03 channel bump.
cc @edolstra
=> NixOS 17.03

nixos/options.tt
Wrap option description in `<para>` instead of `<div>` because some of them expect to be able to close wrapping `<para>` tags and error because of a tag mismatch. Example: https://nixos.org/nixos/options.html#boot.loader.grub.efiinstallasremovable
=> Wrap option description in <para> instead of <div>

logo/nixos-hex.svg
The logo had a soft-coded font in it, which meant that people downloading the logo first had to install that font to render the logo correctly. If not the software (browser, office suite, etc) would fall back to some random font on the system - which may not look very nice and certainly is not likely to result in what was intended by the designer. 
The text part of the logo has been converted to paths, thus avoiding all problems and resulting in a pretty logo everywhere.
=> Update logo with version that doesn't require specific font installed

Makefile
Firstly: I don't know how useful this is as I don't know how often the website is updated.
Apart from that this would allow @AMDmi3 to integrate recent stats into http://repology.org/ helping us keep packages up-to-date.
cc @edolstra
=> Add nixpkgs/packages-unstable.json.gz

nixos/wiki.html
Perhaps not 100% of the content was utterly bad. Add this link for the adventure seekers, hopefully with enough warning that it is possibly broken.
=> Add a link to the nixos wiki on Archive.org

css/nixos-site.css, nixos/packages.tt
A lot of packages have a license object or array thereof rather than a
license string. With this patch, the package search will display all
listed licences, as links to their SPDX page.
Signed-off-by: Ben Kelly <bk@ancilla.ca>
=> Display license information in nix package search

css/nixos-site.css, nix/about.tt, nix/download.tt, nix/index.tt, nixops/index.tt, nixos/community.tt, nixos/packages.tt
First commit improves the places a shell command is on the website, where the `$` of the prompt is placed with CSS. This means that when you copy-paste the line it is impossible to accidentally copy the `$` of the shell.
Second commit creates a `.tt` file containing the sha sums of the nix/install file, making it available in templates.
Third commit updates the "quick" install popup thing to include a sha verification, and a signature verification. I think it is valuable to put these verification steps right up front in order to:
1. demonstrate we care
2. demonstrate they're available, without having to click to the "additional options" page
however doesn't put GPG in the mandatory path for users unless they would like to use it. Additionally:
1. this PR adds a second link to the GPG key, …
=> Verified install steps

Makefile, bootstrapify-docbook.xsl
This fixes https://nixos.org/nixos/nix-pills/why-you-should-give-it-a-try.html's header being "NixOS Manual"
=> On chapter pages, use the value of the 'Home' link as the title

nixos/options.tt
Fixes a bunch of issues:
- Every time the query changed by a character a new entry would be put in history.
- The URL would not update after the last character was removed from the search box.
- If you typed in a valid element id e.g. `search` it would try to jump to that element (which misaligns the search box).
- If you typed in` +` and reloaded the page it would be converted into a space.
- If the query had more then two words it would not replace the additional spaces with pluses.
=> NixOS option search improvements

nixos/options.tt, nixos/packages.tt
In the current page the buttons are displayed at the bottom.
If the alignment of the table above changes the buttons move up and down between pages requiring constant aiming when browsing the result list.
=> Display pager buttons before and after content

nixops/index.tt
The first example originally used Amazon EC2 instances (commit 1d0fe27a314544ec49e75ce268d418a9df2fa01a), but when it was changed to VirtualBox (commit 315405748c68063fa8fc154edc87f9d6f321214c), this sentence continued to reference EC2.
=> fix previous inconsistent edit

nixos/packages.tt
The goal of this PR is to make the *Search NixOS options* feature that synchronizes the search value with the location hash available to the *Search NixOS packages* page:
=> Packages: remember search value in hash

nixos/community.tt
This patch adds the first Stuttgart nixos meetup which will take place in the Stuttgart hackerspace (shackspace.de).
=> Add shackspace/Stuttgart meetup

css/nixos-site.css, index.tt, nix/index.tt
This fixes #67.
* * *
The fix is only applied on "non-mobile" responsive views, as it otherwise adds a *weird margin* to the button, as the button is further from the logo on those resolutions.
An alternative look (e.g. full width) could be defined for the narrower responsive resolutions if desired.
* * *
=> Centers/Aligns `get *` buttons with the snowflake.

Makefile, README.md, nixos/options.tt, nixos/packages.tt
Also change the Makefile to produce packages.json, options.json as
well as options.json.gz and packages.json.gz
This makes it quite a bit easier to test the website locally, and you don't even need a server to do it. Just visiting the HTML file in your browser will do the trick.
=> options, packages: fetch a compressed version only on nixos.org

.gitignore
The goal of this PR is to complete the `.gitignore` file w.r.t. the files created by `nix-shell --run make`.
=> Add `nix-shell --run make` artefacts to `.gitignore`

nixos/support.tt
Add nixos wiki to list of other support sources. Its perfectly fine to be "unofficial".
=> Add nixos wiki to support

css/nixos-site.css
This sets the `pre`'s `overflow-x` to `visible`, which is the initial value, which is overridden by the new `hljs` dependency. Anchor links inside boxes with an `overflow` or `position` set cannot account for the top navbar's height in the first 80px of an element, this is a limitation of how CSS works. This could be worked-around using JavaScript (I think), but the previous behaviour did not cause any issues AFAIK.
After clicking on `(1)`
After clicking on `(1)`
=> doc: overrides `hljs` overflow rules for better linking.

css/nixos-site.css
See: https://twitter.com/kumbunterland/status/982638331757506567
The `<code>` blocks are normally expected to have a `white-space`
property of `normal`, at least I assume docbook would expect the
default. Bootstrap (2.3) changes it to nowrap, which isn't helpful for
an inline type element.
* * *
This is replaced only for the `docbook` pages. If there is somewhere else `<code>` elements are used and exhibit the same issue, the rule can be expanded.
* * *
* * *
cc: @grahamc (in case graham's trying to fix it)
=> Fixes horizontal scrolling originating from `<code>` blocks. (in nixpkgs manual)

css/nixos-site.css, nixos/options.tt
To verify:
* Search using the <input> for `<link`.
* An example option with link: `boot.initrd.luks.mitigateDMAAttacks`
I say this finishes fixing #89 assuming that [the commit that fixed it *partially*](https://github.com/NixOS/nixos-homepage/pull/97) has this description:
> links are still not rendered as HTML links
This now renders the links.
To verify:
* `boot.extraTTYs` has both.
* * *
If there are extra tags I missed, don't hesitate to open an issue and tag me in it.
=> Fixes xml issues in description field for options.html

nix/install.in
This PR will allow users to pass arguments to he installer and have them be passed to the actual installer.
Example:
```
$ cat test.sh 
#!/bin/sh
{
echo "$@"
}
$ cat test.sh | sh -s hi eelco
hi eelco
```
Then, the interior installer can learn `--no-daemon` and `--daemon`, forcing on or off the switch to the daemon installer, overriding any detection done. The nix 2.0-maintenance can then receive the patches  but _default_ to single-user on Linux, but users can override it.
I'm hoping that by merging this PR and a subsequent PR to Nix we can bring back the multi-user installer for Linux 2.0.
=> Allow passing arguments to the Nix installer

nixos/packages.tt
Since https://github.com/NixOS/nixpkgs/commit/aa47bac04f06aeea993dc2e2cc6649fde4f31ed7#diff-94cbd9d7bdc2427d0efb29692838d2c5 these have been showing up as `[object Object]` in the package listing, which is the result of casting an object without a toString method to a string in JavaScript.
This change tries to format them in the same way that they used to be displayed, like `Maintainer Name <name@example.com>`.
Ref: https://github.com/NixOS/nixos-homepage/issues/208
=> nixos/packages: fix maintainer listing (they are no longer strings)

nixos/community.tt
This adds our Discourse to the community page. I copied the description of it from https://discourse.nixos.org/t/welcome-to-discourse/8
=> add discourse to community page

nixos/options.tt
This is safe since all calls to `ppNix` are made using `.text()`.
* https://github.com/NixOS/nixos-homepage/blob/f74049df65db247ce156022155a966c272ffb96c/nixos/options.tt#L324-L328
And *anyway* the previous escapes were done only one time, making it
trivial to bypass
```
> "<<<<<".replace("<", "&gt;")
→ "&gt;<<<<"
```
This has further been manually verified (with an hand-modified options.json) to
not cause opportunities for HTML injection.
=> Removes useless escapes from `ppNix` in options page.

Makefile
Important when a fix is made in nixpkgs when the fix intends to fix the
website generation.
To test, use something like this:
```diff
diff --git a/Makefile b/Makefile
index efc07d3..91479fd 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
NIXOS_SERIES = 18.03
NIXPKGS = https://nixos.org/channels/nixos-$(NIXOS_SERIES)/nixexprs.tar.xz
-NIXPKGS_UNSTABLE = https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz
+NIXPKGS_UNSTABLE = /Users/samuel/tmp/nixpkgs/nixpkgs
rwildcard=$(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2) $(filter $(subst *,%,$2),$d))
```
Then `make nixpkgs/packages-unstable.json.gz`.
=> Fixes build when pointing to a nixpkgs checkout.

index.tt
Template Toolkit doesn't really care about UTF-8, but this ISN'T
template toolit's fault. This was `ucfirst` that was munging the
initial emoji.
* * *
Before this fix:
```
[nix-shell:~/.../nixos/nixos-homepage]$ rm index.html ; make index.html
tpage \
--pre_chomp --post_chomp \
--define modifiedAt="`git log -1 --pretty='%ai' index.tt`" \
--define modifiedBy="`git log -1 --pretty='%an' index.tt`" \
--define root=`echo index.html | sed -e 's|[^/]||g' -e 's|/|../|g'` \
--define fileName=index.tt \
--pre_process=nix-release.tt --pre_process=nixos-release.tt --pre_process=common.tt \
index.tt > index.html.tmp
xmllint --nonet --noout index.html.tmp
index.html.tmp:290: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0x8F 0x83 0xF0 0x9F
<a …
```
=> Fixes emoji titles by uppercasing only letters.

nixos/options.tt
While talking to someone that just started looking into NixOS we figured
out that he wasn't aware that those search results were clickable at
all. While we already changed the cursor while hovering the entries you
would not really be hinted into clicking on them.
This is especially relevant for people using keyboard navigation
(vim-style or similar) since those entries wouldn't show up as
clickable.
With this commit I am just wrapping the text in an anchor tag. That is
enough to make them appear like other links on the website. They also
appear as clickable when using keyboard navigation.
---
=> Make it more obvious that nixos options in the search results are clickable

nixos/packages.tt
It seems to me that any licenses' long name is the most human-friendly attribute for presentation on a website.  `fullName` is intended to be a text string for human presentation.
Then comes SPDX ids (if defined) which were made to be both [human and machine-readable](https://spdx.org/ids).
```scala
nix-repl> stdenv.lib.licenses.bsl11
{ fullName = "Business Source License 1.1"; shortName = "bsl11"; url = "https://mariadb.com/bsl11"; }
nix-repl> stdenv.lib.licenses.lppl13c
{ fullName = "LaTeX Project Public License v1.3c"; shortName = "lppl13c"; spdxId = "LPPL-1.3c"; url = "http://spdx.org/licenses/LPPL-1.3c.html"; }
nix-repl> stdenv.lib.licenses.cc-by-sa-40
{ fullName = "Creative Commons Attribution Share Alike 4.0"; shortName = "cc-by-sa-40"; spdxId = "CC-BY-SA-4.0"; url = …
```
=> nixos/packages: display license long name first

nixos/community.tt
The log archive linked hasn't been updated since 2016. The new one is the one linked in the channel itself: It's up-to-date and searchable.
=> refer to current logs on community page

Makefile
Removing whitespace from packages.json (jq -c .) reduces the gzip-ed size from 3.1M to 2.7M, and the extracted size from 62M to 36M, which might help with parsing and decompressing it quicker.
=> Minify packages.json with jq

nixos/download.tt
In commit 70bcfbb the prefix of the download URLs was changed from
`https://nixos.org/releases/nixos/...`
to
`https://d3g5gsiof5omrk.cloudfront.net/nixos/...`
This doesn't seem ideal since the URL is pointing to a non-NixOS URL. I have
verified that the replacing the Cloudfront URL with `https://releases.nixos.org/nixos/...`
seems to work for all the URLs we care about.
Hence changing the prefix back to NixOS.org's site seems right thing to do.
=> Replaced Cloudfront URLs with NixOS.org URLs

nixos/options.tt
The data was already available!
This uses the (possibly composed) description field from the types.
This was inspired by @ryantm who [was curious about listing the type descriptions on the options page](https://logs.nix.samueldr.com/nixos/2018-10-11#1638655;).
See https://github.com/NixOS/nixpkgs/pull/48251 for better descriptions for `separatedString`.
* * *
=> options: Adds type information to the options list

nixpkgs/index.tt
Message from `nix-2.2.2-x86_64-darwin/install` states `upgrade to 10.10 or higher`.
Also, this comment includes a link to a tag for the last version that supported 10.9: https://github.com/NixOS/nixpkgs/issues/18472#issuecomment-247784839
=> Clarify supported Mac OS X versions

.gitignore, Makefile, css/nixos-site.css, donation.tt, index.tt, layout.tt, news.tt, nixos/index.html, nixos/index.tt
> The nixos.org main page virtually traps the user into the Linux Distribution section of the site. This PR intends to make the different moving parts of NixOS more accessible at first glance.
* * *
> ![image](https://user-images.githubusercontent.com/132835/57343998-84552280-7113-11e9-8663-888c6c49e6d4.png)
The new landing page shows both main components in big visible boxes. The order (left to right) defines their order in narrow mobile layout.
The description was lifted from their respective index pages.
The old nixos.org landing page contents is now the index page of the NixOS sub-section of the site.
When not inside a project-specific sub-section of the site, the menu will show quick access to the main components of the project. Maybe NixOps should be added to it, that's not my call, …
=> Reviews the nixos.org main page

index.tt
We have a link to the Nix page already on the left now. So this link is not needed anymore.
This change should make the page less chaotic.
(I havn't tested to build it.)
cc @samueldr
=> Remove Nix link

nixpkgs/download.tt
it was incomplete and this link is even broken
https://hydra.nixos.org/release/nixpkgs/nixpkgs-0.13/
(I just edited it on GitHub and havn't build it.)
=> Replace list of old releases with link to GitHub

css/nixos-site.css
before & after in the same picture:
This improves other `<command>`s too. After:
before:
re https://github.com/NixOS/nix/pull/3052
=> docs: show <command>s as monospaced

nixpkgs/download.tt
Fixes #80
https://nixos.org/nixpkgs/download.html has a broken link to the unstable manual.
=> Use new link to manual on download page

packages-explorer/src/gui/query.js
Tested the change using `make` then running the python2 http server, as the README states.
The change is rather trivial, and fixes a minor regression that was pointed out by @joepie91.
=> packages-explorer: Adds autofocus

nixos/support.tt
There's already a lot of confusion between the three manuals, because
people can't find the things they're looking for in whichever one they
look at (usually the NixOS manual).  This is even worse when they
don't even know about the existence of the other manuals!
=> nixos/support: link to nixpkgs manual

Makefile, disnix/support.tt, hydra/index.tt, index.tt, layout.tt, nixos/community.tt, nixos/learn.tt, nixos/wiki.tt
Whenever I'm looking for help or documentation, I find it difficult to find it under the word *Support*. 
I find *Learn* to be much clearer.
The idea is that if someone's at the NixOS homepage and looking for help, they're likely newbies (we all have the manuals in our browser histories already I presume).
Someone like that, in my opinion, wants to *learn* what Nix/NixOS is all about, rather than "receive support".
*Documentation* would be another candidate, but we also point to Discourse/IRC rather than just the manual, meaning it's not a good fit.
*Help* is another good option, and I'm honestly not sure which is better between that and *learn*.
This is inspired by Rust's excellent [home page](https://www.rust-lang.org/), and by discussions at the Documentation hackathon at NixCon 2019. …
=> Rename Support to Learn

css/nixos-site.css
On some screen widths (notably those of mobile devices), code blocks can trigger hyphenation:
This can be confusing to users, since the hyphen isn't copied (it's just a CSS artifact), and could cause even more issues if the user is typing these instructions in from another device - in the paragraph just above the screenshot, there is a code block instructing the user to run `systemctl start display-manager` – the hyphen there matters since it's the actual name of the service.
This PR addresses that issue by preventing hyphenation of any `.command` and `.code` blocks, since it appears to be mostly the DocBook-related sections that are most affected:
=> nixos-site.css: Don't hyphenate code blocks

packages-explorer/src/state.js
To save some seconds when doing the occasional lookup, I self-host a mirror of the NixOS `packages` and `options` pages. When serving from a subfolder, e.g. `http://localhost/nixos-homepage/nixos/packages.html`, the usage of absolute paths trips up the data fetching. Changing the paths to relative fixes that.
=> Update packages-explorer to use relative paths.

Makefile, nixos-release.tt, nixos/download.tt
This way we don't have to regenerate the download page whenever the channel updates.
=> Remove latestNixOSRelease

netlify.toml
With the move to netlify, the hydra and nixops manuals vanished, without a redirect. Considering search engines link to those manuals, I believe it's mandatory we keep [cool URIs](https://www.w3.org/Provider/Style/URI.html) working. 
Use a "200" redirect.
> 200: "OK". Redirects with this status code will change the server response without changing the URL in the browser address bar. This is used for rewrites and proxying.
* https://docs.netlify.com/routing/redirects/redirect-options/#http-status-codes
This will keep the nixos.org/.../manual URL in the address bar, but serve the contents proxied from the hydra result.
=> Redirect hydra and nixops manuals to the latest hydra builds

404.tt, Makefile
Closes #343
This works on top of automatic handling by Netlify:
> You can set up a custom 404 page for all paths that don't resolve to a static file. This doesn't require any redirect rules. If you add a 404.html page to your site, it will be picked up and displayed automatically for any failed paths.
* https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling
* * *
I believe the small script to print the URL in the text body is important UX-wise. This will make end-user screenshots or text copy/paste more useful. Sure, it won't work for users who disable scripts, but that's their own decision. The text has been conceived with progressive enhancement in mind.
This is better than:
=> Add custom 404 page

netlify.toml
302s are potentially cached indefinitely and it makes it very hard to change anything in the future.
This also changes `/nixops/manual` to a 200 (netlify proxy).
=> netlify: Change 301 redirects to 302

layout.tt
nixos.org is already index in all the search engines and this is what most people use and search now days happens outside the website. This would of-course not be true if our search would be very tightly integrated with nixos.org.
Other websites I checked (kubernets.io, rust-lang.io) out also don't include this kind of search (full text over all sites) and just rely on google to index them.
I do think we "expose" more search over existing packages and nixos options but that would take some time to get there. first step would be to remove this search in the first place.
=> remove search from the toolbar

flake.nix
This removes the accidental inclusion of /nix/store paths in the packages.json file.
This was part of the original expression:
```
| sed "s|$$nixpkgs/||g" | jq -c . > $@.tmp
```
It was kept as-is, while it's not a Makefile anymore.
Fixes #349.
=> Strip nix store paths from source nixpkgs in packages.json

news.xml
add news date for Release 20.03 using the merge time of NixOS/nixos-homepage#392 (f02e80c7985f1c5ae7659a81ed914c0fcbfcb880)
/cc @worldofpeace
=> add news date for Release 20.03

README.md, news.tt, nix/index.tt, nixos/index.tt
This ended up smaller than intended, as I decided not to bring in some no-op changes from the (upcoming) re-css PR.
They are the changes that are not specific to re-working the CSS.
* * *
This:
* Fixes some links half-broken by moving the download.html page
* Removes use of an unmaintained/unused menu in news.html
Additionally, this documents how to use the python http server with the `result` symlink if you need/want to test with `nix-build`.
What's that with half-broken links? They do work on the website, because of the redirects. Though they don't work on a local setup because the netlify redirect are not available there.
=> Misc fixes around the website

Makefile, guides/contributing.tt, learn.tt
includes removed content from previous community page (https://github.com/NixOS/nixos-homepage/issues/402)
We can make the sections more consistent later and add more information.
=> Add Contributing page

README.md, flake.nix
```
Fixes #410
`git ls-files` only traces files that are already in Git. When adding
new content, this is inconvenient. `fd` searches the entire directory
irrespective of the files' status in Git. However, it still respects
.gitignore files, so that it ignores build artifacts.
```
Hm… this is my first time touching a flake. Traditionally I would have added this package to `shell.nix`. Is it okay to add it under `buildInputs`, even though it is only developer tooling? Or do we have a better place for such things?
By the way git was also not in there… of course, everyone has Git already, making this rarely a practical problem. But still in a pure nix-shell `git ls-files | entr make` fails.
=> Use fd to rebuild untracked files

update.sh
This was renamed upstream, see https://github.com/NixOS/nix/pull/3551
For reference, I ran into this here: https://github.com/NixOS/nixos-homepage/pull/418/checks?check_run_id=663327024
=> Update to use `nix shell` instead of `nix run`

css/nixos-site.css, learn.tt
The comma separated lists are really a display concern, and not a
markup concern - in particular, they're semantically lists.
In addition, laying them out like this means it's easy to forget
to put a trailing comma at the end of the line, like is present on
nixos.org/learn.html at the moment (which currently has:
"[Python], [Ruby] [Java], [Go], [Rust], " - note the missing comma
between "Ruby" and "Java").
=> Fix comma-separated list on /learn.html

css/nixos-site.css, index.tt
Recreated a PR from #438 
This is not trivially screenshotable, you have to compare by resizing the window.
I had to break out of bootstrap for the side-by-side "hero" unit, I can't see a non-hacky way full of custom rules compared to letting the flexbox layout deal with it.
Note that this also adds overflow-x to all the examples at the bottom, which otherwise would be wrapped weirdly. I find that neither options (wrapping weirdly or scrollbars) are satisfactory on wider widths, but on phone widths I know for sure scrolling horizontally those examples is better.
The asciinema box will be weird. I don't know if we can somehow make its text automagically rather than force an horizontal scroll (or worse, cutting off according to its defaults!).
=>  homepage: Fix horizontal scroll on narrower widths

index.tt
The link previously had github instead of github.com
=> Fix a broken link

Makefile, guides/ad-hoc-developer-environments.tt, guides/install-nix.tt, learn.tt
The tutorials are sourced from https://nix.dev. The resulting HTML was adapted to remove Sphinx-specific references and styling.
This is meant to see how it fits into a page to get some first content onto the page.
----
As discussed during the last two marketing team meetings, this only the minimal step one to get some guide-like content onto the page following #418 and @domenkozar launching https://nix.dev. Feedback on the content would be better directed at https://github.com/domenkozar/nix.dev. Also first step of #443.
For next steps I would start automating this integration instead of doing it manually. I'll open a separate issue for that, also to discuss the strategy.
=> Copy first tutorials from nix.dev

Makefile, check-links.sh, features.tt, flake.nix, news.xml
This was #483, addresses part of #481.
Now with preview ;)
This was a bit more involved than initially anticipated. I don't think it's feasible to test local files without a webserver, as the file path semantics are different. There were a bunch of false negatives, as linkchecker simply ignored paths like `/nixpkgs` as they are outside the domain – and they would not work, as they translate to `file:///nixpkgs`.
Starting a local webserver is a heavier approach, but solves the issue. Here I chose caddy instead of, say, `python -m http.server`, because it is quite a bit faster, yet still zero-configuration for this use case. (I also considered lighttpd and busybox httpd, both of which had unsuitable default configurations.)
The `/pkgs/...` routes from the nixpkgs manual are ignored, because …
=> Implement local link checking as part of build

teams/security.tt
The old SKS system is flawed and shouldn't be used anymore. Hagrid (https://sequoia-pgp.org/blog/2019/06/14/20190614-hagrid/) is a relatively new key of replacement for the old SKS system. It strips the signatures from the keys, to prevent key poisoning, so the WoT is dead and gone.
Also key ids  can be cheaply forged, even long ones, see:
- https://debian-administration.org/users/dkg/weblog/105
- https://mailarchive.ietf.org/arch/msg/openpgp/Al8DzxTH2KT7vtFAgZ1q17Nub_g/
Therefore let's migrate to https://keys.openpgp.net and drop key ids entirely.
=> Migrate the security teams GPG key download to keys.openpgp.org

index.tt
I noticed this sentence didn't parse properly because of the extra `'s`.
=> Remove extra characters

css/nixos-site.css, index.tt
The unused IDs were removed.
Fix #489
Note that I haven't removed the use of IDs for other parts. They are probably are not causing conflicts. In the future rework of the site, we'll have to be more mindful and use something like [rscss](https://rscss.io/). And anyway they are pretty well scoped so the risks are quite small.
=> index: do not use IDs for styles

Makefile, flake.nix
This add two new targets (install, clean)
install , which scoops up the artefacts from the build process to build/
flake.nix modified to to make install and copy the build/ dir to $out.
the better way is to modify the make file entirely, but it's not a simple as it seems.
also this might break deployment to netify??????
=> added install and clean targets update flake.nix

Makefile, copy-nix-dev-tutorials.sh
The title was using what amounted to:
```
echo '[% $title %]' > file.tt
```
Which put the literal `$title` perl variable, which in Template Toolkit,
an undefined variable is equivalent to an empty string.
This made the <title /> of the page be "NixOS - Guides - ".
This fixes that by using the better `printf` building for building
strings to print.
Additionally we can drop the empty echoes and use `\n` as printf honours
them.
* * *
In addition, mark the script as an input of those generated files.
=> Fix guides titles (<title>)

index.tt
We're closing the pre-event survey.
I figure that it is good to keep the NixCon 2020 banner itself until the event is completed.
CC @davidak @garbas
=> Remove pre-nixcon survey link. Keep nixcon banner

js/nixos-site.js
We discussed about:
The first two are implemented. See the new custom event for that.
Smooth scrolling using `el.scrollIntoView({ behavior: "smooth" });` does not smooth scroll, AFAICT.
So we would be left to choose an additional JavaScript library to handle the smooth scroll, only for the pane open/close sequence. We apparently can't rely on the browser to smooth scroll the site.
My personal experience with sites that scroll smoothly like that is that it's not ever needed, and most of the time feels wrong. For something I'm not entirely sure is needed.
I'll be leaving the decision for smooth scrolling to you, and I'll implement it if desired. Though it's back at the end of the queue for priorities for the time being. It would take a bunch of time to decide on the better library to use, …
=> redesign: misc. fixes for asciinema panes

demos/example_3.scenario
I think using `mkShell` in a `default.nix` is not something we should encourage.
=> Replace default.nix by shell.nix in screen cast for nix-shell

news.xml
In order to honor the history of Nix(OS), this is an effort to restore
the announcement page to former glory. It is really quite fascinating,
how basically every link before 2010 is broken by now.
Some links are unfortunately beyond rescue, including University Delft
websites that were never archived and now point to a Github 404 …
Things left to do:
- Change all pdfs to archive links. Eelco’s papers still work, but
they shouldn’t change and the links will break eventually. Better
safe than sorry.
- Fix the release pages. From around 2010, a grave sin was commited
and most links point directly to build outputs of hydra.nixos.org,
which are obviously all broken by now. I found that most should be
easy to recover by pointing them to `releases.nixos.org`. Others
might be lost.
- Think about …
=> news.xml: fix links as far as possible

learn.tt, site-styles/pages/learn.less
I would actually prefer 'Nix Manual', 'NixOS Manual' and 'Nixpkgs Manual',
but those documents actually have different titles.
Taking one step at a time, I think changing 'More ...' to 'Manual' is a
good first action :)
=> Learn: replace 'More ...' with 'Manual'

learn.tt
This makes it clearer what the 3 'Read more...' buttons actually point to, and
that they are pointing to 3 different manuals.
Seems to fit fine on all zoom levels / window sizes I tried, and is helpful
especially in the mobile view where the 3 sections are actually below each
other rather than next to each other.
=> Label buttons to the manuals with the manual names

index.tt
As there is no isolation and all of these shells are still able to wipe
all of your data we should probably not call them "isolated". They are
probably better described as `declarative` as that is what is happening
here.
=> index: Rename "isolated" to "declarative" example

index.tt
The 2020.nixcon.org site now has a schedule widget. Point the link to that.
=> Point link at schedule

download.tt, js/nixos-site.js, site-styles/components/collapse.less, site-styles/components/flair.less, site-styles/components/footer.less, site-styles/components/index.less, site-styles/components/navbar.less, site-styles/components/notice-box.less, site-styles/components/tabs-navigation.less, site-styles/layout.less, site-styles/mixins.less, site-styles/pages/download.less, site-styles/pages/index.less, site-styles/theme.less
- [Download_deskop_2.pdf](https://github.com/NixOS/nixos-artwork/blob/master/www/2020_redesign/Download/Download_deskop_2.pdf)
- [Download_mobile_2.pdf](https://github.com/NixOS/nixos-artwork/blob/master/www/2020_redesign/Download/Download_mobile_2.pdf)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/594)
=> Download page redesign

download.tt
And one instance where it was simply dropped. Being irrelevant.
cc @worldofpeace; fixes #613
=> download.tt: KDE → Plasma

features.tt
When trying to learn how nix works through the features page, I had a lot of trouble understanding this section. We discussed it here https://discourse.nixos.org/t/site-intro-to-nixs-repeatable-builds-point-has-some-clarity-issues/9154/4 , and eventually things were explained to me. Accordingly, I have changed the section so that it will be more clear for new users.
In short, saying "compilers don’t search in per-packages
directories such as
<tt>/nix/store/5lbfaxb722zp…-openssl-0.9.8d/include</tt>,"
Is very confusing for a new user, because they are trying to understand how compilers actually do find their way into nix's store when they're allowed to, and this comes across as if it's saying that they don't. It is in fact a regular occurrence for compilers to "search" those directories, …
=> made the complete dependencies paragraph in features.tt a lot clearer for new users

site-styles/pages/manual.less
It breaks prompts among other things:
https://nixos.org/manual/nixpkgs/stable/#sec-patches
=> manual: do not use normal whitespace in code

learn.tt
afaict https://nix-cookbook.readthedocs.io just redirects to nix.dev @domenkozar
=> Rename Nix cookbook -> nix.dev

site-styles/components/asciinema.less
fixes #597 
> The reason there was that aspect ratio thing there was to, if I remember
> right, make the whole player fit in the height of a side-ways mobile
> device.
> 
> Though I think I must have forgotten to finish implementing this, as
> instead it just resolved to using the default font sizes.
> 
> Rather, let's do what works fine for every other sizes: a ratio of the
> device width.
— @samueldr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/637)
=> site-styles: Fix asciinema breaking width by removing aspect ratio code

download.tt
The GNOME ISO correctly detects and configures HiDPI scaling.
More, it supports changing the scale. The Plasma Desktop ISO
doesn't detect and configure the scale automatically, and doesn't
allow you to change it without restarting. This makes the GNOME
ISO significantly more accessible for users on laptops with HiDPI
displays.
=> NixOS Download: recommend GNOME

download.tt
Reverts NixOS/nixos-homepage#642
From that PR:
> The GNOME ISO correctly detects and configures HiDPI scaling.
> More, it supports changing the scale. The Plasma Desktop ISO
> doesn't detect and configure the scale automatically, and doesn't
> allow you to change it without restarting. This makes the GNOME
> ISO significantly more accessible for users on laptops with HiDPI
> displays.
Bringing this back to the table. After discussing it with @worldofpeace, they +1'd. Maybe let's hear from @jonringer too.
=> Revert "Revert "NixOS Download: recommend GNOME""

layout.tt
This used to be a rather vague statement, because "NixOS" is not
the name of a person or legal entity.
Nobody has signed away their copyright, so it remains with the
individual contributors.
This is not legal advice.
=> Copyright notice: NixOS -> NixOS contributors

site-styles/pages/community.less
Fix #682 by adding styling for `governance-description`.
This shall affect every pages that lies under `community/teams`.
=> styling: add styling for governance-description

community/index.tt
We've closed `Meetup-NixOS-Montpellier` group on Meetup.com (not open source, too expensive…). The same group is now "NixOS Montpellier" (alias "nix-mtp") on mobilizon.fr.
=> Montpellier moved from Meetup to Mobilizon

community/index.tt
To make it easier to contact them.
Ideally though, the foundation would have its own email address.
=> index.tt: add emails of Foundation board members

flake.nix
aiohttp will use cchardet to determine the charset of the page it
retrieves if it's available and isn't specified in the Content-Type
header. In the case of some of the sources it isn't specified, which
leads to problems when parsing them.
This fixes the failed updates - https://github.com/NixOS/nixos-homepage/runs/2535903129?check_suite_focus=true.
=> update-blog: add cchardet dependency

netlify.toml
Untested, but based on https://github.com/NixOS/nixos-homepage/pull/709 and https://docs.netlify.com/routing/headers/.
=> Add CORS policy for matrix client endpoint

scripts/copy-nix-dev-tutorials.sh
Otherwise, search engines deemphasize both sites as they duplicate content.
=> Tell crawlers that the canonical url for guides is at nix.dev

layout.tt
Previously the first picture would be shown instead of a NixOS related
image when a NixOS.org website is referred to from Matrix, Discourse
etc..
=> Add og:image to your layout

community/index.tt, community/teams/security.tt, layout.tt
This removes the links to the abandoned `#nixos` channel on Freenode, and replaces the link to the `#nixos-security` by the corresponding Matrix room.
There are still some references to the `#nixos-marketing` channel, but we don't have an equivalent Matrix room yet.
=> Remove freenode links

community/index.tt, layout.tt
ea454f3 ("Remove references to abandoned #nixos channel") removed the
references to Freenode, but didn't replace them with anything, even
though we didn't stop using live chat -- we moved to Matrix.
Here, I've re-added links to Matrix where we used to link to Freenode.
=> Add links to Matrix

community/index.tt, site-styles/pages/community.less
Established May 7 this year with Armijn, Rob, and Eelco. At the time,
it was primarily shared on Twitter:
https://twitter.com/grhmc/status/1390775249424338944
I should have added it to the website then, but now is a good time
too.
=> Add the NixOS Foundation's statement of inclusion

site-styles/pages/community.less
before: ![image](https://user-images.githubusercontent.com/1229027/125860704-63bedfa4-1e9f-4257-97b7-591c10463f24.png)
after:
=> styling: fix width of commercial support logos

community/commercial-support.html.in, community/commercial-support.toml
removing nixcloud.io from the commercial list. unfortunately nixcloud.io is out of business and does no longer exist as a company.
=> removed nixcloud.io (out of business)

netlify.toml
When trying to build a very old version of Nixpkgs, from 2009, I wasn't able to download the bootstrap tools.  It was trying to download them from <http://tarballs.nixos.org/stdenv-linux/x86_64/r13932/bootstrap-tools.cpio.bz2>.
Now, the curl in this ancient Nixpkgs doesn't support https, but if there'd been a redirect, at least as a user I'd have been able to nix-prefetch-url it to add it to the store manually, instead of guessing where it might have moved.
=> Redirect old bootstrap tarball URLs

community/commercial-support.html.in
In d0ac4b15 parts of the shellHook that describe how to
hack on the website were accidentally committed as part of the
commercial-support page.
Fixes: #750
=> commercial-support: Drop accidentally committed devdocs

scripts/update-blog.py
Currently external pages with umlauts are parsed erroneouly similar to the following: `"Höse".encode("utf8").decode("cp1252")` -> `'HÃ¶se'`.
Reported on Matrix by @samueldr.
=> scripts/update-blog.py: Pass response as raw bytes to feedparser

flake.nix, scripts/copy-nix-dev-tutorials.sh
https://github.com/NixOS/nixos-homepage/commit/f3ba34321f38e372a05a2f3f2eb53a46a1a43c45 updated nix.dev flake to a version using a different theme:
https://github.com/nix-dot-dev/nix.dev/commit/d177dba53b5dae69bc3347b8c58aee30af7e186f
This patch adjusts the XPath expressions to match what sphinx-book-theme uses. Unfortunately, the theme just uses anonymous divs so the XPath is not very robust.
Fixes: https://github.com/NixOS/nixos-homepage/issues/768
cc @domenkozar
=> Fix Nix.dev guides

blog/announcements.xml, learn.tt
Including the archive links from https://github.com/NixOS/nixos-homepage/commit/412c3eb79e365540dcec71970f1b69c54f84dffd
Used `linkchecker --config=<(echo '[AnchorCheck]') --check-extern https://nixos.org/` to find the issues but it is super noisy (anchorcheck is somewhat broken and GitHub kept giving me 503 errors).
Fixes: https://github.com/NixOS/nixos-homepage/issues/756
=> Fix broken Nix manual links

Makefile, blog/index.tt, download.tt, learn.tt, scripts/copy-nix-dev-tutorials.sh
- Add missing tutorials from nix.dev
- Move `Install Nix` tutorial to be included in Download page
- Fix link to PatchELF
=> Sync with nix.dev

download.tt
As of Nix 2.4, the `--darwin-use-unencrypted-nix-store-volume` flag was
deprecated and prints a warning. Single user installations on macOS are
no longer supported so the `--daemon` flag is unnecessary.
=> Remove installer flags deprecated as of Nix 2.4

community/teams/security.tt
The PGP keys on the security page are expired.
```
pub   rsa4096/0xFE918C3A98C1030F 2014-01-04 [SC] [expired: 2021-01-04]
Key fingerprint = BA94 FDF1 1DA4 0521 2864  C121 FE91 8C3A 98C1 030F
uid                   [ expired] Graham Christensen <graham@grahamc.com>
uid                   [ expired] Graham Christensen <graham@tumblr.com>
uid                   [ expired] Graham Christensen (Contractor) <graham@clarify.io>
pub   rsa4096/0x846FDED7792617B4 2010-05-28 [SC] [expired: 2020-09-16]
Key fingerprint = 8A39 615D CE78 AF08 2E23  F303 846F DED7 7926 17B4
uid                   [ expired] Franz Pletz <fpletz@fnordicwalking.de>
uid                   [ expired] Franz Pletz <fpletz@bpletza.de>
uid                   [ expired] Franz Pletz <fpletz@franz-pletz.org>
uid                   [ …
```
=> security: Remove refs to expired PGP keys

flake.lock, scripts/bootstrapify-docbook.xsl, site-styles/pages/manual.less
When an admonition contained other elements than paragraphs (e.g. pre), they were removed. Additionally, custom titles were replaced in single-paragraph admonitions by generic ones and all titles were stripped in multi-paragraph ones.
With this patch, the stylesheet should preserve all contents of admonitions when trying to Bootstapify them.
Noticed by @maralorn and reported on [Matrix](https://matrix.to/#/!kjdutkOsheZdjqYmqp:nixos.org/$pwoosV97vjUhIwO-Lh-18MJvvvDTAmF67sHC-FazFDs?via=nixos.org&via=matrix.org&via=nixos.dev).
[![Note in manual on the website](https://user-images.githubusercontent.com/705123/144734619-9226a713-c8d5-429f-9ff6-1232c21b614c.png)](https://nixos.org/manual/nixos/stable/index.html#sec-booting-from-usb)
=> manual: Prevent the stylesheet from eating the admonition contents

download.tt
The URL for the nix package manager release notes does not include the
patch version when the patch version is `0`, i.e. on new minor and major
releases. This currently causes a broken link on download page to the
release notes of the latest version of nix.
For example, the download page currently generates a link for
`release-notes/rl-2.6.0.html`, however the actual URL for the release
notes is `release-notes/rl-2.6.html`.
This commit removes the patch version from the URL to the release notes
when the patch version is `0`.
=> Fix broken URL to release notes

Dockerfile, README.md, docker-compose.yml, scripts/serve.py
This PR removes the dependency on `nix` to be in the developer's environment and adds docker as an alternative.
Related to #833
I'm probably not the only person here who would like to contribute to the homepage and nix/nixos documentation,
but doesn't necessarily have `nix` itself installed on my dev machine or in my dev environment.
There are probably other usecases as well, but for me personally, I main a non nixOS distro (opensuse) and don't want to take
my chances of messing up this install. So, nixOS is on a separate laptop which is purely for testing nixOS and doesn't have
my developer secrets.
This helps me contribute and might help others contribute who just swing by and don't want to install yet another tool
in order to contribute just some HTML or CSS.
=> Add docker-compose

download.tt
There is a [long-standing issue](https://github.com/NixOS/nix/issues/2374) where the multi-user installation fails on systems that enable SELinux. The user then gets to clean up the nixbld users and whatnot.
Unfortunately, the Download page is not very helpful. While it recommends the multi-user installation only for supported systems, it doesn't link to the [manual page that specifies these](https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation).
I considered adding said link, but I think it's better to mention it directly. The wording is copied directly from the manual.
=> Specify supported Linux platforms on Download page

community/index.tt
NixOS Discourse is the central community platform and should be listed
first.
=> where to talk: make forum first list item

learn.tt
the words "in the beginning" were heavily misleading. user feedback
consistently shows that the Pills are too low level to be useful as an
introduction.
=> move Nix Pills to the end of list, reword logline

learn.tt
Noticed that the link on the [learn page](https://nixos.org/learn.html) for Javascript was broken (well, it pointed to a non-existent anchor on the page), this PR fixes that.
=> learn.html: fix broken language section anchors

netlify.toml
@garbas this is broken right now since the last Nix release. The previous PR only had redirects for the `unstable` branch.
=> Nix language manual redirect for all versions

blog/announcements-rss.xsl
Previously it pointed at a URL which just redirected here.
=> Fix self link in RSS feed.

flake.lock, flake.nix
Pills now have an EPUB output so we need to update the attribute name.
Depends on: https://github.com/NixOS/nix-pills/pull/189
=> flake: Update pills attribute reference

community/teams/rfc-steering-committee.tt
This catches up on the rotation of 2022 as well as spacekookie's departure from the team.
=> Update steering committee

Makefile, community/index.tt, community/teams/nixpkgs-architecture.tt
Adds the [nixpkgs architecture team](https://github.com/nixpkgs-architecture/) to the team listing. Also improves the team listing a bit:
- Renames the buttons to "Read more" instead of "Members & Contacts". All of these links give you more info on the team, it's not just the people in them
- Adds some dots to sentences in the team listing for consistency
=> Nixpkgs architecture team (and some small team page improvements)

index.tt
According to https://github.com/NixOS/nixpkgs/blob/cfaec958cc81014eae1b8f35827c7c46b4c74207/README.md there are more than 80,000 packages in the nixpkgs repository. 
(According to https://repology.org/repository/nix_stable_22_05 there are about 86K total.)
=> 60,000 -> 80,000 packages in nixpkgs

download.tt
1. replace git@github.com  to https://github.com
2. also add `--depth=1` to clone fastly
=> download.tt: update git URL to avoid permission issue

community/teams/nixpkgs-architecture.tt
=> Remove Tweag sponsorship note from Christian Hoeppner

Makefile, scripts/copy-nix-dev-tutorials.sh
tracking nix.dev this way doesn't scale and has to be reworked if we
want to ramp up tutorials and guides on nix.dev
@LucPerkins @bryanhonof
=> fix link to Nix language tutorial

download.tt
The aarch64-linux ISOs are part of the nixos-unstable and unstable-small jobsets and exposed through the nixos-channel-scripts.
This means they will be available for the upcoming NixOS 22.11 release and can be linked from the homepage.
=> download.tt: Expose aarch64-linux ISOs for 22.11

download.tt
Currently the link on read-only root directs people to the multi-user installation instructions. Where-as the section on "MacOS Installation" is the part where it actually explains about read-only root.
This PR changes the link so that it directs to "MacOS Installation"
=> download: fix MacOS manual link

flake.nix
Otherwise they get [added](https://github.com/NixOS/nixos-homepage/blob/d5c136aed7f9d2d72bef29b912c1a7514d8940fb/scripts/update.sh#L15) to the live site:
I didn't update the page to avoid a merge conflict with the automated action.
=> flake.nix: Don't print the instructions on stdout

flake.lock, flake.nix
I used release-22.11 in the nixos 22.11 announcement, because nixos-22.11 hadn't progressed far enough yet. Let's revert back to the cached version now that it has caught up.
=> Migrate the stable nixpkgs input to nixos-22.11

community/teams/nixos-release.tt
Update link from it used to be located on the release manual in nixpkgs to the current rendered release wiki markdown repo.
=> Update release wiki link

community/teams/documentation.tt
Thanks for all the work! I see myself already be saturated with writing documentation for my own projects. I fail to keep track with all the work that the documentation team and the community is doing and hence I feel like I do not have much to contribute to the regular meetings.
In case someone wonders, this is not related to
https://discourse.nixos.org/t/parting-from-the-documentation-team/24900 in any way. I have not followed what happend there and this decision to step back has been already made before.
=> stepping back from documentation team

scripts/copy-nix-dev-tutorials.sh
The "Next steps" section of https://nixos.org/guides/towards-reproducibility-pinning-nixpkgs.html contains a link to itself, ie to
https://nixos.org/guides/towards-reproducibility-pinning-nixpkgs.html
This is wrong. If you go to the original article at https://nix.dev/tutorials/towards-reproducibility-pinning-nixpkgs you can see that the link actually points to https://nix.dev/reference/pinning-nixpkgs.html#ref-pinning-nixpkgs
Afaik, this article doesn't exist on nixos.org, so I'm fixing this by linking the original article on nix.dev
=> fix self-reference link inside a guide

community/teams/documentation.tt
Valentin never left the docs team, but he was mistakenly removed in https://github.com/NixOS/nixos-homepage/pull/922.
Luc is not team lead anymore and effectively stepped down from the team after the drama from
https://discourse.nixos.org/t/parting-from-the-documentation-team/24900, see https://matrix.to/#/!avYyleMexqjFHoqrME:nixos.org/$QYprG8cyv4zbj3qk9lMeJm9_z07xbjknsWfQ6T2Zs6w
=> doc team: Remove Luc, readd (mistakenly removed) Valentin

community/teams/documentation.tt
Previously it was unclear if the company was just who you're part of, or actually sponsored
Ping @fricklerhandwerk, discussed in this week's doc team meeting
=> Explicitly mention sponsorship for the docs team

community/teams/documentation.tt
employment and funding in the consulting space are distinct things, and
in this setup there are indeed two principals one has to know to have
the correct impression of affiliations
@infinisil for double-check
=> documentation team: disclose affiliation precisely

download.tt
We should not only tell users that they need to run the installer, we also need to tell them how to. Thus, link to the install section of the manual here.
---
Closes #1013 
CC @fricklerhandwerk
=> Link to installation section

learn.tt
Fixes https://github.com/NixOS/nixos-homepage/issues/1019
=> Fix the broken `Building Your Own NixOS CD` link on Learn page

site-styles/pages/community.less
This prevents the bottoms and tops of buttons on multiple rows touching when using a narrow-ish viewport.
Closes #1050 (see for original screenshots).
With a single-column viewport:
With a multi-column viewport:
=> community: add top/bottom margin to buttons (closes #1050)

layout.tt
So interested people find it
Not built and tested if it breaks the layout. Maybe text is too long.
=> Add "Reproducible Builds Status" to footer

blog/announcements.xml
The existing description was lacking and needed clarification.
Contiuation of #1067
=> blog: Update libxcrypt changes announcement for 23.05

community/index.tt, community/teams/marketing.tt
as developed by @garbas and some members of @nixos/marketing-team, me mainly acting as a scribe.
this concludes a series of discussions and clarifications.
the change also removes the FAQ that sounded needlessly apologetic, also
because all rationale should be provided in the mission statement.
=> add marketing team mission and strategy

community/index.tt
Sorry for the trouble, I was able to join with the old url, but multiple people reported problems with the nerdberg.de domain so I changed it to matrix.org.
=> fix Nürnberg meetup url

netlify.toml
follow-up to #1054 to preserve existing links and bookmarks.
from now on nix.dev should take care of its own URLs being stable.
=> add redirects to moved nix.dev articles

community/teams/moderation.tt
https://discourse.nixos.org/t/welcome-martin-weinelt-to-the-moderation-team/29345
=> add hexa to moderation team

flake.lock
Two issues are preventing the CI to work correctly again:
- https://github.com/NixOS/nixpkgs/pull/239986 - https://nixpk.gs/pr-tracker.html?pr=239986
- https://github.com/NixOS/nixpkgs/pull/240327 - https://nixpk.gs/pr-tracker.html?pr=240327
We need to wait for both of them to be propagated in `nixos-unstable` branch before updating `flake.lock` file again. In the meantime, updating it is useless.
=> Fix nixos/manual building by updating the flake `released-nixpkgs-unstable` input

.github/workflows/cron.yml
Hi,
This opinionated PR proposes the following changes:
1. Changes the `cron` workflow from running `hourly` to `daily`
2. Remove obsolete options that are enabled by default on some actions
3. Reformat the file using `prettier`: `nix run nixpkgs#nodePackages.prettier -- --write .github/workflows/cron.yml`
=> ci: `cron`: Update from hourly to daily

learn.tt
The link to "First steps with Nix" point to nix.dev. This changes the link to a more specific tutorial on nix.dev titled "First Steps", which makes more sense given the title of the button.
=> learn: link to First Steps tutorial

index.tt
NixOS does not support reproducible builds* so having this be the first word gives people the wrong impression considering how well-known this project is.
"Declarative" conveys the intent better.
* As defined by the Reproducible Builds projects
=> index: replace Reproducible with Declarative.

community/commercial-support.tt
I'm no longer operating Black River Software, so it should be removed from the list of Nix/NixOS service providers.
=> Remove Black River Software [no longer operating] from service providers

community/commercial-support.tt
Somehow this got mixed up with mayflower. I am not re-adding mayflower since I have sources that most (all?) NixOS-related people will have left the company by next year.
=> commercial-support: fix url for serokell

flake.lock, flake.nix, scripts/update.sh
The nix.dev flake changed the output schema in
https://github.com/NixOS/nix.dev/commit/957bda73d48d40132a36159eb7392d3a03e92ebd
This failed the last attempted automated CI update:
https://github.com/NixOS/nixos-homepage/actions/runs/6700205463/job/18205745665
=> Fix nix.dev

netlify.toml
blocked by https://github.com/NixOS/nix/pull/7974
=> add redirect to catch removed Nix manual page (basic package management)

community/teams/nixcon.tt
The NixCon team is transitioning.
For more information, please see the discourse post: [Governance through “project leads” in NixCon 2024](https://discourse.nixos.org/t/governance-through-project-leads-in-nixcon-2024/33981)
=> Update NixCon team

.github/workflows/cron.yml
This enables the [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger, allowing the daily updates to be trigger manually from https://github.com/NixOS/nixos-homepage/actions/workflows/cron.yml
I want this so I can link people to new sections in the Nixpkgs/NixOS manual without having to wait for the daily update.
Also, so I can force an update already now, since updates were broken [for 5 days](https://github.com/NixOS/nixos-homepage/pull/1163#issuecomment-1827677297).
=> Allow triggering manual updates

community/teams/nixpkgs-architecture.tt
Voluntarily on their own in todays meeting: https://github.com/nixpkgs-architecture/team-log/commit/2578a77fff8c6519c24acc80f2bc5d19293af50d, https://github.com/nixpkgs-architecture/meetings/blob/master/2023-11-28.md
=> @phaer leaves the Nixpkgs Architecture Team

src/components/ui/Button.astro
Fixes the lg-full size in the Button component as mentioned here: https://github.com/NixOS/nixos-homepage/pull/1164#issuecomment-1845426366
=> Astro/Fix Button component for size lg-full

src/components/ui/Tag.astro
Fix Tag component:
- so hrefs work.
- uses the correct 'nix blue' value.
- so the background fits the contents. Without the `w-fit` class it looks like the bottom tag instead of the top.
=> Astro/Fix Tag Component

.github/workflows/cron.yml
The current default for cachix/install-nix-action@v24 is 2.19.1, which annoyingly completely removed support for `--update-input`, which the homepages udpate script was relying upon. Only 2.19.2 reinstated support for that flag with a deprecation notice.
Also by pinning we prevent such problems in the future. Notably in this case this caused the docs on nixos.org to not update **for 2 months**.
I tested the script locally. After merging I'll manually trigger the action
=> workflows/cron: Pin Nix to 2.19.2, fix updates

community/teams/moderation.tt
The previous address is still intact, but since it led to confusions we went to clear this up.
=> Update the moderation team email address

site-styles/pages/blog.less, site-styles/pages/main.less, site-styles/pages/manual.less
A scrollburglar is an issue mainly affecting mobile devices where scrolling down (e.g. by dragging up with your finger) often unintentionally results in a horizontal scroll due to the page content overflowing the viewport width. (I believe this was coined by [Josh W. Comeau](https://www.joshwcomeau.com/).)
The scrollburglar instances I noticed were on the [blog page](https://nixos.org/blog/) and [some](https://nixos.org/manual/nixos/stable/) of the [manual pages](https://nixos.org/manual/nixpkgs/stable/). You can open the mobile view in Firefox with the shortcut `Ctrl+Shift-M`. (It's also possible in other browsers.)
I tried to limit the scope of the `display: inline` applied to `code` elements in case the original `display: inline-block` was important in some contexts.
- [`overflow-wrap: …
=> fix(style): eliminate some scrollburglars

netlify.toml
The Hydra manual in the current location has not been updated since 2022, as the jobset was split into architecture-specific variants.
=> Update link to latest Hydra manual job

src/components/pages/download/DownloadAccordion.astro
Removing the download tabs  `<span>` attribute since it causes problems and is unneeded anyway
=> Download: fix tab navigation by removing unnecessary span

README.md
Following the instructions at https://github.com/badges/shields/issues/8671. I have also formatted the badges into separate lines for better diffing in future.
I'm a little confused on the presence of both master and main branches, but I follow the label and other badges and direct this badge at the master branch.
=> readme: fix workflow status badge

src/content/teams/01_foundation-board.mdx, src/content/teams/09_cuda.mdx, src/content/teams/11_documentation.mdx
This gives users the choice to use their own Matrix client instead of Element, and it also shows a nicer landing page instead of immediately going to the Element web app. This is already used for most of the Matrix links, there are just a few which use app.element.io.
Builds successfully and all affected links seem to work correctly. I've copied the links below if you would like to try them:
- https://matrix.to/#/#docs:nixos.org
- https://matrix.to/#/#cuda:nixos.org
- https://matrix.to/#/#foundation:nixos.org
Old link for comparison:
- https://app.element.io/#/room/#docs:nixos.org
=> teams: use matrix.to instead of app.element.io for links

src/components/pages/community/CommunityLink.astro, src/pages/community.astro
I have left Stack Overflow in the main section because it is an already moderated property on the web.
Feel free to add a commit moving it if you believe this is not appropriate.
This also changes the style of the section slightly by not growing the buttons, as they become a bit too *ｗｉｄｅ*.
Wide:
Narrow:
=> community: Split talk section according to moderation status

flake.lock, flake.nix
since most flake dependencies are pretty outdated and nix also has a new version, I bumped the flake dependencies manually.
To keep up with nodejs versions without big migrations, I updated nodejs from the last LTS release `18` to the current LTS `20`.
=> Update flake.lock and bump NodeJS 18 -> 20

.github/workflows/cron.yml
I noticed the [cron workflow](https://github.com/NixOS/nixos-homepage/actions/workflows/cron.yml) has been broken for a while, when I was looking into whether some changes I made on the Nixpkgs/NixOS manual had already propagated to the homepage.
The YAML file had an error because it started the `if` condition with a `!` without escaping it. The [GitHub docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) mention this case:
> You must always use the ${{ }} expression syntax or escape with '', "", or () when the expression starts with !, since ! is reserved notation in YAML format.
This PR fixes this by following the same syntax as shown in the example in the GitHub docs link above.
=> Fix YAML for cron workflow

src/content/download/02-nix-macos.mdx
This bugged me on the download page, so I know it'll bug others. Every set of instructions for the other platforms shows the `$` prompt (or [other prompt where relevant](https://github.com/NixOS/nixos-homepage/blob/main/src/content/download/04-nix-docker.mdx)), but the macOS one doesn't. 
This commit just adds a `$ ` for consistency. 
Seemed like a simple enough change that I just opened a PR; let me know if there needs to be a corresponding issue.
=> Show shell prompt in macOS install instructions

public/demos/cover.scenario, public/demos/example_1.scenario, public/demos/example_2.scenario, public/demos/example_3.scenario, public/demos/example_4.scenario, public/demos/example_5.scenario, public/demos/example_6.scenario, src/components/ui/Asciinema.astro, src/pages/index.astro
Fixes https://github.com/NixOS/nixos-homepage/issues/1323
Let asciinema handle responsive design by setting `fit: 'width'`
https://docs.asciinema.org/manual/player/options/#fit
This is the default option but it is currently false.
It seems like we need to make a tradeoff between fitting all the text in
or having a larger font. I'm betting on showing all the content being
the more important of the two and that we can have terminal replays with fewer columns
if we really want larger font. And it's easier to rely on asciinema's
player to be responsive than to adjust font size manually ourselves.
- deleted `terminalFontSize` per docs that this is only relevant if fit is set to false.
- Set width to 100% instead of max-width for the asciinema examples
`max-width: 100%` resulted in these player …
=> Make asciinema responsive with fit: width

flake.lock, flake.nix
Since https://github.com/NixOS/nix-pills/pull/233 got merged, the nix pills are now built with mdBook. In this process, we removed the `revCount` and `shortRev` attributes from the mdBook output.
This PR removes those attributes from here to ensure the nix pills can still be built with the new changes.
=> Fix nix pills build with new mdBook output

flake.nix
Rewrote the input declarations to fall within an overarching inputs structure scope. This manages to vividly distinguish the inputs from the succeeding cache configurations before the outputs declaration.
=> Minor minimization of inputs redundancy in flake.nix

README.md
changed link from `master` to `main` to correctly refer to the main branch
=> Update README.md, correcting an invalid hyperlink to master branch

src/content/teams/10_nix.mdx
Having spoken with Nix team members, it looks like all are equally empowered, and that it's inaccurate to call Eelco the team lead.
See also https://discourse.nixos.org/t/nixos-foundation-board-giving-power-to-the-community/44552/7?u=infinisil
Ping @NixOS/nix-team, please review
=> Fix Eelco's Nix team title

src/content/teams/02_rfc-steering-committee.mdx
@jonringer has voluntarely stepped down from the committee with a message in the internal Matrix channel.
I thank you for your time on the steering committee, even if it was just brief!
=> Update RFC Steering Committee after jonringer stepped down

src/pages/guides/how-nix-works.mdx
This pull request adds a missing "be" to the body of ["How Nix Works"](https://github.com/NixOS/nixos-homepage/blob/022865693e96ea1c32335c18aecd93388ce9dd2a/src/pages/guides/how-nix-works.mdx).
=> Proofreading "How Nix Works"

src/components/pages/community/teams/MembersDisplay.astro, src/content/teams/08_moderation.mdx, src/pages/community/teams/[...slug].astro
resolves  #1420
(Please don#t merge this with the changes to moderation, this is just an example to preview the changes here, I'll remove them before merging since the commits get squashed anyway)
=> add implementation for subteams

public/well-known/matrix/client, public/well-known/matrix/server
We are moving away from EMS and towards self-hosted infrastructure.
cc NixOS/infra#336
Migrated from PR #1218
=> well-known: delegate matrix client/server to matrix.nixos.org

.github/workflows/update-flake-lock.yml
For the past 2 months, the Nixpkgs for the manuals was not updated because of this!
#ZurichZHF
- Fixes https://github.com/NixOS/nixos-homepage/issues/1431
- Fixes https://github.com/NixOS/nix/issues/10743
- Fixes https://github.com/NixOS/nixos-homepage/issues/1412
=> Make the regular update action update all flake inputs

public/netlify.toml
nix.dev serves stable URLs to the manual, and has redirects for the
`stable` and `unstable` mutable URLs. it also re-uses page-level
redirects that are supplied by the Nix manual itself, so we don't have
to take care of that here any more.
Made with @roberth at #ZurichZHF
=> redirect all Nix manual URLs to nix.dev

public/netlify.toml
undo another error introduced in rewiring the Nix manual URLs.
Discovered by @GreatTeacherOni https://github.com/NixOS/nix/issues/9349#issuecomment-2143051011, thanks!
=> fix confusing redirects

public/netlify.toml
The redirect for the hydra manual link points to the job "manual" which seems to have been deleted in 2022, replaced by "manual.x86_64-linux" and "manual.aarch64-linux".
I don't know how much the manuals differ by architecture, if at all, but I'm guessing x86-64 is reasonable target here.
=> Fix redirect for hydra manual

.github/workflows/ci.yml
Changing the deploy trigger to `pull_request_target` to allow the CI to use our secrets for deployments regarding PRs from forks, making PR checks quicker and less error prone over time.
See here for details: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
=> Change Github Actions trigger type to pull_request_target to prevent tampering and allow workflow from forks

src/pages/community.astro
Add the links to our calendars under `/community`
@fricklerhandwerk @infinisil
Can we figure out who is responsble for maintaining what i linked here as the "official calendar" ?
Please feel free to make changes.
=> Calendar: init - add links to the common calendars

public/netlify.toml
Tested with netlify-cli!
Note that this changes semantics, and now redirects `unstable` to the latest Nix version rather than to the most recent build from `master`.
This is to avoid
- either more downstream errors with "pretty URLs", which are not supported by Hydra
- or expensively re-building the manual on nix.dev regularly just to work around Hydra's limitations
This is probably what we want.
I assume that most people will use the latest Nix release rather than `master`.
For those who live on `master` there's still https://nix.dev/manual/nix/development, and presumably being power users they will hopefully know that.
Closes:
- https://github.com/NixOS/nix.dev/issues/1005
- https://github.com/NixOS/nix.dev/issues/1006
- https://github.com/NixOS/nixos-homepage/issues/1483
- …
=> fix more broken URLs

src/pages/community.astro
Requested that the calendars don't take up the full width but use a 3 column grid like the rest of the elemnts.
https://github.com/NixOS/nixos-homepage/pull/1488#issuecomment-2198243157
=> calendar: fix grid columns

src/components/util/InlineSVG.astro, src/pages/learn.astro
- extend the Intrinsic svg html attributes 
instead of explicit type cast, which is more unsafe
- Add `as const`
Which creates more narrow type unions for e.g the color "lightblue" | "orange" | "green" instead of "string" for the non-const expression
=> fix: some types of InlineSVG

src/content/learning-manuals/01-nix-manual.mdx
Seems like [the link](https://nixos.org/manual/nix/stable/expressions/expression-language.html) to the language docs on https://nixos.org/learn is dead. Checked with archive.org and it used to redirect to https://nixos.org/manual/nix/stable/language/index.html so I updated it.
=> fix: broken link to language overview in manual

src/content/teams/10_nix.mdx
this information has been asked for repeatedly and otherwise requires
finding the right link and traversing a fairly large document to access.
=> add link to Nix team meeting information

flake.lock
Flake lock file updates:
• Updated input 'released-nix-stable':
'github:nixos/nix/f1ab41b2bc2b070a5b9c1b7b4ef20cc7b84b1e58?narHash=sha256-mYvdPwl4gcc17UAomkbbOJEgxBQpowmJDrRMWtlYzFY%3D' (2024-09-03)
→ 'github:nixos/nix/f1deb42176cadfb412eb6f92315e6aeef7f2ad75?narHash=sha256-lAoLGVIhRFrfgv7wcyduEkyc83QKrtsfsq4of%2BWrBeg%3D' (2024-07-05)
• Removed input 'released-nix-stable/git-hooks-nix' • Removed input 'released-nix-stable/git-hooks-nix/flake-compat' • Removed input 'released-nix-stable/git-hooks-nix/gitignore' • Removed input 'released-nix-stable/git-hooks-nix/nixpkgs' • Removed input 'released-nix-stable/git-hooks-nix/nixpkgs-stable' • Updated input 'released-nix-stable/libgit2':
'github:libgit2/libgit2/36f7e21ad757a3dacc58cf7944329da6bc1d6e96?narHash=sha256-J2rCxTecyLbbDdsyBWn9w7r3pbKRM …
=> flake.lock: downgrade latest Nix to 2.23

src/content/download/02-nix-macos.mdx
Same premise/language as https://github.com/NixOS/nix/pull/11487
The impending release of macOS 15 Sequoia will break many existing nix installs on macOS, which may lead to an increased number of people who are looking to try to reinstall Nix without noticing the open/pinned issue (NixOS#10892) that explains the problem and outlines how to migrate existing installs.
These admonitions are a short-term measure until we are over the hump and support volumes dwindle.
=> add admonitions for macOS 15 Sequoia update

src/content/teams/03_security.mdx
Announcements are now made in a distinct category.
=> teams/security: update link to the security announcement category on Discourse

src/content/teams/14_xen.mdx
I have no idea how I only noticed this after the merge. I'm truly sorry.
=> teams/xen: fix typo

src/content/download/52-nixos-amazon.mdx
Filters combine with OR, not AND. So the instructions were wrong.
=> Fix typo in AWS AMI search instructions

src/pages/values.astro
Small follow-up to https://github.com/NixOS/nixos-homepage/pull/1541 now that the more long-term https://github.com/NixOS/org/blob/main/doc/values.md exists.
The intention is that people don't update the values by making a PR to the homepage, but rather the other repo.
=> Mention the source of truth for the values

src/components/ui/Asciinema.astro
Click title for asciinema-player doesn't run player, because logic is described outside the scope of the variable "player".
=> Fix asciinema-player

.gitignore, flake.lock, flake.nix
This PR adds
- flake-parts to the flake
- a git hook that checks formatting on push
- npm package installation if node_modules does not exist to prevent errors when pushing
The reason I set on-push for the hooks is, that people could get quite annoyed when having to check for proper formatting on every commit. Since we doe merge PRs anyway, we can require proper formatting on push and ease local development for contributors.
I'd like to hear feedback from other contributors here on what to add or to change before I merge this into main.
=> chore: convert flake to flake parts and add git-hooks

src/pages/blog/[category]/[year]/[id].astro
The change in this PR shows the blog post title in the page title. Closes #727.
=> blog: show post names in titles

README.md
Updated the README to include new information about how people can contribute to the repository. The was based on discussion in the marketing team meeting on 2025-01-13.
=> readme: update/add contribution guide

src/content/teams/07_marketing.mdx
Updates members and roles based on a recent marketing team meeting on 2025-01-13. https://github.com/NixOS/marketing/blob/3fb403ccd7982d09ef8c584660b67770003f7213/minutes/2025-01-13.md
- Adds Florian to the team.
- Adds roles based on the meeting.
- Re-organizes member order.
=> marketing-team: update members and roles

src/content/teams/08_moderation.mdx
We prefer being contacted via Discourse DM to make sure we can all have access to reports and prevent bottlenecks.
=> Moderation: update reporting issues section

src/content/blog/newsletters/2019_07-nixos-19-03-release-ipfs-ci-integrations-and-documentation-feedback.md
This is a technical fix in the frontmatter (metadata) of the newsletter dated 2019-04-17.
The properties starting in capital result in the `blog/feed.xml` showing incorrect details for the post.
=> fix typo in frontmatter of 2019-04-17 newsletter

src/content/download/04-nix-docker.mdx
Closes: #1415 
I tested the commands in the docs on my local and they failed then I tested the edited commands in the issue reply by [@mcdonc](https://github.com/mcdonc) and they worked.
The original fails because we mount `/nixpkgs/` to `/nixpkgs` in the previous command `docker run -it -v $(pwd)/nixpkgs:/nixpkgs nixos/nix` instead of '/'. I think this is intentional, however it means that `default.nix` is located at `/nixpkgs/default.nix` and has to be specified in the `nix-build` command.
=> Fix command in nixpkgs docker instructions

flake.nix
Since the `nix` manual is now handled by nix.dev, this PR omits it from the website build process.
=> Remove nix doc generation form build process

src/content/learning-manuals/01-nix-manual.mdx
The "What is a channel?" link in the manual goes to a page not found. I think `nix-channel` is close enough if that's meant to be kept around
=> Fix broken channels link

src/content/download/02-nix-macos.mdx
This adds a sentence explaining to macOS users how to open the terminal. Fixes #1116.
=> download/nix/macos: add instruction to open terminal

astro.config.mjs, src/components/pages/blog/BlogListEntry.astro, src/components/pages/download/DownloadAccordion.astro, src/content.config.ts, src/lib/utils.js, src/pages/blog/[category].astro, src/pages/blog/[category]/[year].astro, src/pages/blog/[category]/[year]/[id].astro, src/pages/community.astro, src/pages/community/teams/[...slug].astro, src/pages/index.astro, src/pages/learn.astro
Fixes: https://github.com/NixOS/nixos-homepage/issues/1611
Following https://docs.astro.build/en/guides/upgrade-to/v5/#updating-existing-collections, changes of the same type are grouped into commits
- turn off legacy.collections and define `src/content.config.ts`. Previously we were getting the content config autogenerated by directory. This is technically still available as a deprecated feature, but it wouldn't work for us anyway because it only globs on md/mdx files
```
Auto-generating collections for folders in "src/content/" that are not defined as collections.
This is deprecated, so you should define these collections yourself in "src/content.config.ts".
The following collections have been auto-generated: blog, community, download, explore, landing, landing-features, …
```
=> Migrate to Astro 5 content layer API

src/components/pages/community/CommunityPageListItem.astro
This did not render correctly on mobile.
We did not catch that, sorry.
Before this fix:
After this fix:
=> alternative implementation: fix rendering on mobile

flake.nix
`aarch64-darwin` does not exist under `htmlDocs.nixosManual` (which
makes sense because nixos would preclude darwin), so hardcode to
`x86_64-linux` instead.
Similar precedent https://github.com/NixOS/nixos-homepage/pull/1470
This fixes this error when running `npm run dev` inside the dev shell
```
error:
… while calling the 'derivationStrict' builtin
at <nix/derivation-internal.nix>:37:12:
36|
37|   strict = derivationStrict drvAttrs;
|            ^
38|
… while evaluating derivation 'manuals'
whose name attribute is located at /nix/store/jl0f72iyvv0cj1r5qrqmpi9cvi1dfcxp-source/pkgs/stdenv/generic/make-derivation.nix:375:7
… while evaluating attribute 'buildCommand' of derivation 'manuals'
at /nix/store/jl0f72iyvv0cj1r5qrqmpi9cvi1dfcxp-source/pkgs/build-support/trivial-builders/default.nix: …
```
=> Fix homepage build on macOS darwin

.github/workflows/ci.yml
This PR enables preview builds for forks and hardens the CI by stripping unnecessary and potentially dangerous permissions that have previously been in place.
=> Make preview builds work for forks and harden CI

core/src/content/menus/footer.yaml
This PR renames the NixOS Newsletter link to better help to avoid confusion about its state and how we are handling it currently. This is the result of the discussion in [a previous meeting](https://discourse.nixos.org/t/2025-03-24-marketing-team-minutes/62125).
=> rename newsletter link and move it down

core/src/content/teams/01_foundation-board.mdx
The [version from the constitution](https://github.com/NixOS/org/blob/main/doc/constitution.md#nixos-foundation-board) is the latest revision, so should also be used for the website. Ping @NixOS/foundation
=> Update board responsibilities to match the constitution

core/src/content/teams/14_xen.mdx
- Adds back @digitalrane, as noted in https://github.com/NixOS/nixpkgs/pull/393306.
- Adds a link to the Xen Security Policy if anyone looking at the team page is interested in learning more about how Xen (and therefore the maintenance team) handles security.
=> teams/xen: sync with Nixpkgs' team list; minor improvements.

core/src/lib/utils.js
Modifies the `createExcerpt` function to remove h1, h2, and h3 headings from excerpts so the summaries are more legible.
=> feature: remove headings from excerpts

core/src/pages/learn.astro
The previous wording was unnecessarily imprecise:
“a wiki” instead of “the wiki”, “user-maintained”, no mention of “official”.
The new wording keeps the connotation of welcoming user contributions (and makes that more explicit), but also makes it clear that this is the official one.
(Created as part of #ZurichZHF)
=> learn: clarify that we link to *the* official wiki

core/src/content/teams/15_ngi.mdx
- Remove offer to apply: Application phase for 2025 has ended.
- Add office hours information.
- Closes ngi-nix/summer-of-nix#148.
=> NGI@Nix: update team's infos

core/src/pages/community/event-funding.mdx
While the new @NixOS/foundation board is evaluating the financials and prioritisation of funding, we need to be a bit more conservative with event funding.
Note that event funding requests submitted in the past are unaffected.
This change was agreed-upon by all @NixOS/foundation board members.
=> NixOS Foundation board: Update event funding limits

core/src/components/pages/community/teams/MembersDisplay.astro, core/src/content/teams/08_moderation.mdx, core/src/pages/community/teams/[...slug].astro
- List all the members in the Members panel on the right hand side
- Clarify the role of the "subteams" - as they're called in the code
I hope my phrasing does it justice. Feel free to make suggestions @Lassulus and other team members.
=> Clarify team membership on moderation page

core/src/content/community/meetups.yaml, core/src/pages/community.astro
1. Add link to Socal NUG homepage in meetups
1. Add link + text to direct people to nix.ug
Preview of changes
=> add socal nug + link to nix.ug

core/src/pages/community.astro
The current link is to the Determinate Systems website (https://determinate.systems), which is (a) more of a marketing vehicle and (b) not currently in great shape (on that page). The official documentation (https://docs.determinate.systems) is much more relevant to readers of nixos.org.
=> Update Determinate Nix link
