NixOS/nixos-homepage

- nixos/packages.tt
@edolstra could you please test this? i was not able #50
> package search: fixes #48 Nix expression link broken

- nix/install.in
from https://github.com/NixOS/nix/issues/747
> installation script needs bash

- docs/papers.xml
- nixos/community.tt
@edolstra, is the VVSS-2007 link acceptable?
> Update some dead links

- common.tt
- disnix/docs.tt
- disnix/download.tt
- disnix/examples.tt
- disnix/index.tt
- disnix/support.tt
- docs/papers.xml
- hydra/index.tt
- news.xml
- nix/about.tt
- nix/download.tt
- nixops/index.tt
- nixos/about.tt
- nixos/community.tt
- nixos/download.tt
- nixos/packages.tt
- nixos/support.tt
- nixpkgs/download.tt
- patchelf.tt
Change many HTTP URLs to use HTTPS instead, where the resource to which
the URL refers is available via HTTPS.
> Change many HTTP links to HTTPS

- nix/install.in
Fixes regression introduced by dc30713b14db73de61b85501aa1ce32d7e23fc34
@edolstra This is in reference to the comment I posted on your commit.
> nix/install: Run the installer after download

- nixos/community.tt
This PR adds Nix/NixOS meetups links to the community page.
> community page: add meetups information

- nixos/community.tt
> Change mailing list archive link

- nixos/community.tt
> Add London NixOS meetup

- nixos/support.tt
Would it make sense to publicize the consulting companies that offer nix support?
There is a bit of a conflict of interest but it might also help adoption.
/cc @edolstra @domenkozar @jagajaga @qknight @seitz
> Add list of Nix consulting companies

- nixos/support.tt
> Add mention of the security releases mailing list

- nixos/options.tt
This allows people to link to an option search directly.
> allow sharing option searches

- disnix/index.tt
Just noticed a few little typos while reading this.
> Fix a few typos in summary description

- Makefile
- nixos/wiki.html
Looks like https://codepen.io/gchristensen/project/full/XxvnoD/
re https://github.com/NixOS/nixos-org-configurations/pull/30
cc @copumpkin
> nixos/wiki: init to handle wiki requests

- news.xml
Promote the NixCon a bit more. It would be better to have a big banner I think but this is already better.
> news: add NixCon 2017

- Makefile
Fixes NixOS/nixpkgs#27237.
cc @edolstra @globin @FRidh @volth
> Fix packages-unstable.json.gz regeneration

- Makefile
- news.xml
> NixOS 17.09

- nixos/download.tt
...as I had to point it out to a prospective user, who'd just skimmed the headers.
> Make the USB stick option more obvious

- disnix/support.tt
- hydra/index.tt
- news.xml
- nixos/community.tt
- nixos/support.tt
This is a proposal to make the switch to reduce the number of discussion platforms that we use.
> Replace nix-devel by Discourse

- nixos/security.tt
Resolves [issue 251](https://github.com/NixOS/nixos-homepage/issues/251) re: outdated security page.
> updated sources of security information; removed a dead key

- donation.tt
- nixos/foundation.tt
Expand the role of the foundation, scale of the infrastructure.
Looks like this:
> Refresh the foundation page

- layout.tt
I'll check if there are some easy SEO tricks for the manuals we could do.
> Grant google search console access

- nixos/support.tt
> Obsidian Systems provides commercial support too

- nixpkgs/index.tt
Updates the minimum version reflecting changes in nixpkgs-unstable.
> Update minimum macOS version

- nixos/download.tt
Here's the correct CLI instructions on how to create a nixos virtual machine on Azure. The vhd v16.03 on the homepage does not work but this is being resolved at https://github.com/NixOS/nixpkgs/issues/36262. This pull-request can and should be merged before then.
> corrected az cli instructions for nixos on azure

- donation.tt
- nixos/foundation.tt
- replaces paypal donations with OC
- remove outdated transparency report
> Add Open Collective to improve transparency

- LICENSES/CC-BY-SA-4.0.txt
- LICENSES/MIT.txt
- README.md
This repository should have an open source license!
The suggestion is to use:
- CC-BY-SA for website content (including artwork)
- MIT for source code (same as nixpkgs)
Next steps:
1. First we need to find a consent for licenses to use. Please provide feedback!
2. To license the contributions, we need every contributor to accept the license. If someone don't accept or we can't reach them, we have to rewrite the contribution!
License accepted:
Close #121
> Add licenses

- nixos/community.tt
> Add New York Nix Users Group

- .gitignore
- Makefile
- flake.lock
- flake.nix
- nixos/options.tt
- packages-explorer/src/state.js
- update.sh
Note: the nixpkgs-unstable channel hasn't updated yet, but the options/packages from nixos-19.09 work.
> Get packages.json and options.json from channels.nixos.org

- governance.tt
- teams/discourse.tt
> add Discourse Team

- news.xml
removed duplicate link (i just opened every link and one was the same URL, bad UX)
also removed `.` in the brackets
> clean up news

- nixos/options.tt
> Handle null values in attrsets option examples

- Makefile
- download.tt
- flake.lock
- flake.nix
It's very outdated.
Also update this flake to use NixOS 20.03.
> Remove Azure/GCE image tabs

- netlify.toml
Came up in https://github.com/NixOS/nixos-homepage/issues/406
> Add redirect for /nixos/support.html

- Makefile
- commercial-support.tt
- learn.tt
includes removed content from previous community page
also removes content that is already on the community page and links to 
it instead
> Add Commercial support page

- .github/workflows/cron.yml
The problem was fixed in https://github.com/github-actions-x/commit/pull/15
> Fix commiting to master branch from cron action

- teams/nixcon.tt
@andir @zimbatm @flokli what do you think about this change?
> Make call more visible on NixCon Team page

- commercial-support.tt
> Add Tweag to the list of companies providing support

- css/nixos-site.css
- layout.tt
@davidak I only provided some structure and style. It is a start and we can start adding links to the footer.
Fixes #361
Closes #358
> Add footer

- .github/workflows/cron.yml
- .github/workflows/main.yml
- .gitignore
> report hourly failures to webmaster email

- js/nixos-site.js
- layout.tt
Options search simply doesn't work, it goes to the packages search.
Packages search doesn't work because it tries to use `nixos-undefined` as a channel. Look at the commit for more information why.
Fixes #436
> Fix bugs related to search on the index page

- commercial-support.tt
Adding my company as one of providing Nix/NixOS professional support.
> commercial-support: add five binaries

- netlify.toml
please review
fixes https://github.com/NixOS/nixos-homepage/issues/439
> Create redirect for /nix

- flake.nix
> use released-nixpkgs (aka nixos stable) channel to track nix releases

- demo.scenario
This fixes some grammar and improves wording in the demo.
I want to add that I'm not a native English speaker myself, so I'd appreciate a review from someone who is. :-)
> Improve some wording in the demo

- download.tt
> correct link to older nix releases

- guides/ad-hoc-developer-environments.tt
- guides/contributing.tt
- guides/install-nix.tt
- js/nixos-site.js
- layout.tt
- learn.tt
- nixos/options.tt
- nixos/packages.tt
- teams/discourse.tt
- teams/infrastructure.tt
- teams/marketing.tt
- teams/nixcon.tt
- teams/nixos_release.tt
- teams/rfc-steering-committee.tt
- teams/security.tt
> move search from navigation bar to learn page

- demo.scenario
> Fix the file name bat opens

- download.tt
- features.tt
- index.tt
otherwise it gets copied
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/494)
> Space should be part of the prompt

- index.tt
Here and there sentences didn't read like native English.  Also, the word "Docker" should be capitalised.
> index.tt: Minor updates to wording.

- .github/workflows/main.yml
- flake.lock
- update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/511)
> disable (temporary) updating of nix unstable flake

- Makefile
- css/nixos-site.css
- flake.lock
- js/manual-version-switch.js
- update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/516)
> Bring back nix unstable manual

- index.tt
Closes https://github.com/NixOS/nixos-homepage/issues/512
The design is not supposed to look good, just be acceptable.
We will have a new design soon.
The content should be good.
Feel free to suggest better wording!
> Add pre-nixcon survey banner

- .github/workflows/master.yml
- .github/workflows/pulls.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/523)
> Fix broken netlify deployment

- flake.lock
- flake.nix
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/525)
> Switch nixpkgs input from 20.03 to unstable

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pulls.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/527)
> add cachix to speed up the builds on github actions

- Makefile
- layout.tt
- site-styles/components/form-elements.less
- site-styles/components/navbar.less
It was missing from its previous implementation.
This adds a bit of machinery in the layout where we are templating the links for the header.
Simply done for now.
> re-design: Implement navbar active state

- commercial-support.tt
- community.tt
- donate.tt
- features.tt
- governance.tt
- js/nixos-site.js
- site-styles/assets/svg.less
- site-styles/assets/title-angle.src.svg
- site-styles/assets/title-angle.svg
- site-styles/components/banners.less
- site-styles/components/flair.less
- site-styles/components/index.less
- site-styles/components/tabs-navigation.less
- site-styles/layout.less
- site-styles/pages/donate.less
- site-styles/pages/guides.less
- site-styles/pages/index.less
- teams/marketing.tt
- teams/rfc-steering-committee.tt
- teams/security.tt
Subject to review: Any page where the equivalent `.tt` source file has been edited. Any of the pages untouched, or discussed in the next section are not to be tested or reviewed yet.
* * *
We're left with:
* learn
* download
* manuals
* ~~guides~~
The learn page needs a bit more care than the basic MVP, but as stated in the last meeting, this'll be done with minimal implementation, not the full blown re-design
The download page will need even more care than the basic MVP, compared to learn. But still, not the full blown re-design yet.
The manuals should be almost ready, but I know there were some things to review.
~~(new from merge with master) guides will need a bit more work...~~
* * *
Open questions
* Tabs styling... see the donate page. This is extremely an MVP.
> re-design: MVP all (most) pages

- demos/cover.scenario
- demos/example_1.scenario
- demos/example_2.scenario
- demos/example_3.scenario
- demos/example_4.scenario
- demos/example_5.scenario
fixes #530
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/531)
> add header to asciinema videos

- Makefile
- demos/example_6.scenario
- index.tt
- layout.tt
- site-styles/components/demo.less
- site-styles/pages/main.less
This PR fixes:
- Why choose Nix or NixOS? title removed
- In "why Nix" section we should hide those gray circles until they are designed (at the end)
- remove "Install Nix” button from navbar
- one more example added (eg. NixOS test)
- replaced the lorem ipsum in other examples 
- fixed items in the footer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/535)
> improve content on the landing page

- index.tt
- js/nixos-site.js
- site-styles/components/banners.less
- site-styles/components/flair.less
- site-styles/components/footer.less
- site-styles/components/form-elements.less
- site-styles/components/navbar.less
- site-styles/layout.less
- site-styles/theme.less
I'm not positive on the wording, but the long sentence didn't feel right.
Compare to mockups:
Implementing the numbers on top of days for only days would be quite cumbersome. Furthermore, it's not like it's really important to have a second-by-second countdown for now.
I don't think it would be *too* time consuming to also add more than days, and to make it update, but I'm not really sure it's worth it for the time being.
Let's see your thoughts all and see how this evolves?
> redesign: Add events banner (with NixCon banner)

- site-styles/components/footer.less
- site-styles/components/navbar.less
- site-styles/layout.less
I wasn't trying to be flippant in a66b8e1d96621d7cc2257bc73452201e04c35115, it causes misc. issues around the site as this adds borders to links *wholesale*.
Some links are "structural" in the site; they are `display: block` to fill their parent element to make a bigger touchable target.
The best example of an issue this change causes is in the tabs navigation:
This is not the only issue this causes, but this is the most obvious.
* * *
What is the desired outcome of replacing the font-engine-native underline with a border? I don't see how this is improved.
The font-engine-native underline does things a border cannot do, like not striking through descenders.
While a border can do things the font-engine-native underline cannot do, but here it's not being done. Things like using a dotted or …
> Re-do "improve links"

- teams/nixcon.tt
> Add addict3d to nixcon team

- index.tt
It looks really weird when the line is broken in the middle of '60 000'
> Don't break '60 000'

- demos/cover.scenario
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/548)
> nix-shell in recordings should be (green) the same

- demos/example_6.scenario
Fix typo, see https://github.com/NixOS/nixos-homepage/pull/506#issuecomment-694303994.
> demos/example_6.scenario: fix typo

- demos/cover.scenario
- demos/example_1.scenario
- demos/example_2.scenario
- demos/example_3.scenario
- demos/example_4.scenario
- demos/example_5.scenario
- demos/example_6.scenario
Thanks for the redesign, the new page is awesome!
This are some tiny improvements to language in the screen casts on the web page.
On some I am sure, some might be controversial.
Disclaimer: I am not a native English speaker, but I think what I am suggesting are improvements.
> Fix various typos or formulations in screen casts

- demos/example_4.scenario
fixes #554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/559)
> typo in minimal docker image example

- demos/example_2.scenario
fixes #558
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/563)
> typo in example 2 scenario

- js/nixos-site.js
- layout.tt
- learn.tt
- site-styles/pages/learn.less
fixes #553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/564)
> Bring back search boxes on the learn page

- demos/cover.scenario
> Replace default.nix by shell.nix in cover screencast.

- README.md
fixes #569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/571)
> fix instructions how to build and serve website locally

- learn.tt
> Unify capitalisation of manual headings

- demos/cover.scenario
- demos/example_3.scenario
- demos/example_4.scenario
- demos/example_5.scenario
- demos/example_6.scenario
fixes #561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/573)
> use `cat -n` instead of `bat`

- download.tt
fixes #499
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/576)
> Only we only provide hvm-ebs esc images

- demos/cover.scenario
- demos/example_4.scenario
since it is not possible to do on macosx
fixes #514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/577)
> enforce building docker images on linux

- bootstrapify-docbook.sh
fixes #417 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/578)
> remove pre-git/post-git from the nixpkgs manual

- demos/example_6.scenario
It accepts attrset arguments directly without callPackage-style indirection.
> Simplify nixosTest demo

- site-styles/components/flair.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/549)
> on mobile page have less margin-bottom between page-title and content

- layout.tt
- site-styles/components/navbar.less
- site-styles/mixins.less
fixes #545
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/575)
> Use search icon instead of search input box in the navbar

- flake.lock
- flake.nix
fixes #541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/585)
> bump asciinema-scenario to 0.2.0 via overlay and update nixpkgs flake

- site-styles/components/demo.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/586)
> fixing broken preview video link

- news.tt
- news.xsl
- site-styles/layout.less
- site-styles/pages/news.less
Fixes #543.
Read the commits for implementation details :).
> Fix news page breaking out of the layout

- site-styles/assets/svg.less
- site-styles/components/asciinema.less
- site-styles/components/banners.less
- site-styles/components/choice-smorgasboard.less
- site-styles/components/clickable-whole.less
- site-styles/components/demo.less
- site-styles/components/flair.less
- site-styles/components/footer.less
- site-styles/components/form-elements.less
- site-styles/components/gfx-alternating-side.less
- site-styles/components/navbar.less
- site-styles/components/notice-box.less
- site-styles/components/pane.less
- site-styles/components/tabs-navigation.less
- site-styles/configuration.less
- site-styles/layout.less
- site-styles/mixins.less
- site-styles/pages/donate.less
- site-styles/pages/guides.less
- site-styles/pages/learn.less
- site-styles/pages/main.less
- site-styles/pages/manual.less
- site-styles/pages/news.less
- site-styles/responsive.less
- site-styles/theme.less
- site-styles/vendor/asciinema-player.less
- site-styles/vendor/sdr-responsive/debug.less
- site-styles/vendor/sdr-responsive/responsive.less
@samueldr You told me that you plan to do this after the redesign, but I thought we might as well do it now. Also feel free to close the PR if you don't want to do it now.
I used the following command:
```
find site-styles  -type f -name "*.less" -exec sed -i "s/\t/  /g" {} +
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/591)
> tabs -> spaces in less files

- site-styles/components/flair.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/603)
> center page title on mobile (xs)

- netlify.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/605)
> add calendar to the site

- .github/config.yaml
- .github/content_issue.md
- .github/design_glitch.md
> Add issue templates

- index.tt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/621)
> Commenting the NixCon banner

- teams/nixos_release.tt
> nixos_release: add jonringer as manager

- download.tt
- js/nixos-site.js
> download.tt: Fix EC2 Launch buttons

- css/nixos-site.css
This reverts commit a90a642429cfa1ce604b2c389ff3775527a431ce.
It's still in use by status.nixos.org.
> Revert "css: Remove now unused nixos-site css"

- download.tt
fixes #627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/631)
> Removing the number in Nix download section

- layout.tt
- site-styles/components/footer.less
- site-styles/components/navbar.less
- site-styles/debug.less
- site-styles/index.less
- site-styles/mixins/layout.less
- site-styles/mixins/utilities.less
- site-styles/pages/community.less
- site-styles/pages/learn.less
This PR closes #634.
* * *
With this, we also gain a new debugging superpower: the site width is always shown with yellow rulers. In addition to this, columns are pink, and the flexible spacing helpers are orange and green.
(What does this mean? Scroll down to the NixOS logo in the footer and double click the lambdaflake.)
* * *
These are all issues I've had to fixup following through actually fixing what #634 fixed (which was not fixing the issue it tried to, this is for another PR.)
Mostly things that were found out to accidentally align invisibly with an additional stray "gutter" width to the right. Comparing the site with the live one you should see *some* changes at many places columns are used. For some it might have changed how the text can flow.
This does address the stray padding …
> misc. alignments and columns fixes

- download.tt
Reverts NixOS/nixos-homepage#641 Let's go back to Plasma until @worldofpeace / @jonringer take a looksee.
> Revert "NixOS Download: recommend GNOME"

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pulls.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/644)
> Update GitHub actions

- Makefile
- copy-nix-dev-tutorials.sh
- flake.lock
thank you @domenkozar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/646)
> learn: adding terraform guide from nix.dev

- explore.tt
Someone pointed out the cool graphics on the [Explore page](https://nixos.org/explore.html) and I noticed some typos while checking it out.
> Proofread explore page

- .github/workflows/cron.yml
- .github/workflows/master.yml
- .github/workflows/pulls.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-homepage/654)
> add nix profile to PATH

- demos/cover.scenario
A bit wordy though. Feel free to improve it.
> Avoid "magic"

- Makefile
- flake.lock
- site-styles/index.less
- site-styles/pages/index.less
- site-styles/setup.less
> Update nixpkgs flake input

- community/teams/rfc-steering-committee.tt
> Update RFC Steering Committee membership

- donate.tt
Signed-off-by: Rob Vermaas <rob.vermaas@gmail.com>
> Update bank account for NixOS Foundation.

- donate.tt
It should probably say "money" instead of "mone".
> Fix typo in donate.tt

- download.tt
https://discourse.nixos.org/t/nix-2-4-released/15822/6
> Fix manual links, remove source tarball link

- guides/how-nix-works.tt
> remove spaces to fix misindented lines

- blog/announcements.xml
My fiance noticed that there was an extra slash.
She's very disappointed by us, "nerds".
> Remove extra slash

- Makefile
Tools like https://technicalseo.com/tools/robots-txt/ report that the file is
invalid.
/cc @zupo
> robots.txt: fix typo

- Makefile
> Brings back "How nix works" page

- blog/announcements.xml
- blog/announcements.xsl
- index.tt
reviving the release announcements on the nixos.org
> Nix 2.6.0 announcement

- scripts/copy-nix-dev-tutorials.sh
> Fix how we extract the title from nix.dev

- blog/announcements-rss.xsl
- blog/announcements.xml
ids were needed to link to specific announcement
> Link element added to RSS feed for announcements

- scripts/copy-nix-dev-tutorials.sh
> Fixes the broken link in guides

- blog/announcements.xml
- index.tt
and also backfill the announcement for 2.7.0
> nix 2.8.0 announcement

- layout.tt
https://docs.joinmastodon.org/user/profile/#verification
> Add 'rel="me"' link to verify our Mastodon presence

- learn.tt
this makes it addressable by anchor link
> add id to manuals section

- community/teams/security.tt
I've discussed it with Franz Pletz and we agree it is best to cycle him out in favor of some more active contributors.
> Security team: replace Franz with Linus and hexa

- download.tt
I saw there was some confusion about this somewhere, though I don't remember where...
> mention you can install other desktops

- Makefile
- community/teams/documentation.tt
also fix website rendering errors
> update documentation team info

- netlify.toml
depends on https://github.com/NixOS/nix/pull/6863
> add redirects to accommodate changes in Nix manual

- index.tt
- layout.tt
fixes https://github.com/NixOS/nixos-homepage/issues/707
> NixOS -> Nix in page titles

- Makefile
- flake.nix
> Makefile: copy nix-pills epub

- community/index.tt
- community/teams/documentation.tt
- community/teams/marketing.tt
- community/teams/rfc-steering-committee.tt
- download.tt
- explore.tt
- index.tt
- layout.tt
- learn.tt
- scripts/update-blog.py
> make titles work without prefix

- scripts/copy-nix-dev-tutorials.sh
addresses https://github.com/NixOS/nixos-homepage/issues/671#issuecomment-791353841
> refer to original nix.dev guides

- community/commercial-support.toml
> fix the numtide metadata

- community/teams/nixpkgs-architecture.tt
Every existing member accepted the application
Ping @aakropotkin :)
<https://github.com/nixpkgs-architecture/team-log/commit/da5c58ad3539db1e865cc0c551afdda3b58d5045>
> Nixpkgs Architecture Team: Add Alex Ameen

- community/teams/documentation.tt
depends on https://github.com/NixOS/nix.dev/pull/346
> migrate information on documentation team to GitHub

- community/teams/nixpkgs-architecture.tt
https://github.com/nixpkgs-architecture/team-log/commit/3a19d63eb758ce788a3c88d53f6234955ce61a29
> Remove Christian Höppner from the nixpkgs architecture team

- Makefile
- community/index.tt
- community/teams/nix.tt
- donate.tt
- site-styles/pages/community.less
This is mostly copied from https://discourse.nixos.org/t/nix-team-creation/22228.
> Add Nix team page

- flake.lock
- scripts/copy-nix-dev-tutorials.sh
And update locked nix.dev
Supersedes #966, this PR is tested locally
Ping @NixOS/documentation-team
> Fix broken link to contributing guide

- community/index.tt
As per discourse post: https://discourse.nixos.org/t/expanding-the-nixos-foundation/19929
Fixes https://github.com/NixOS/nixos-homepage/issues/933
> updating nix board members.

- learn.tt
also slightly reword information on the other learning resources
> add The Nix Hour

- download.tt
Releases are not signed any more: https://github.com/NixOS/nix/pull/7411
> remove "Verify installation" section

- community/event-funding.tt
@domenkozar not sure if this is what you want to say
original: https://github.com/NixOS/nixos-homepage/pull/989#discussion_r1106020244
> event funding: clarify phrasing

- community/teams/moderation.tt
The Moderation Team has unanimously agreed to accept @alyssais's application to join the team. Thank you for volunteering to help moderate our community and welcome!
> [moderation team] add Alyssa Ross as member

- community/teams/nixos-release.tt
Well, hello, I will do my best. :)
> Update release managers for 23.05

- Makefile
- flake.nix
- index.tt
- layout.tt
- scripts/bootstrapify-docbook.sh
- scripts/copy-nix-dev-tutorials.sh
>  Add a description meta tag 

- netlify.toml
blocked by https://github.com/NixOS/nix/pull/7979
> add redirect to catch removed Nix manual page

- community/index.tt
Adding the nixos nürnberg user group
> Add Nürnberg meetup

- community/teams/nix.tt
Source: https://github.com/NixOS/nix/blob/60f06a1714a74bf144eb9ccad9643578248bdfc4/maintainers/README.md?plain=1#L37
> List myself as a Nix team member

- community/commercial-support.tt
Follow up of #1081 , remove duplicated entries.
> commercial-support: remove duplicated entries

- community/commercial-support.tt
Follow up of #1083 , fix link.
> commercial-support: fix edit link

- .github/workflows/cron.yml
- .gitignore
> ci: fix auto-commit action, remove non-existent file

- layout.tt
I didn't actually check if the icon works, so don't merge without checking
> treewide: add mastodon to footer

- community/teams/nixpkgs-architecture.tt
All current members accepted their applications
https://github.com/nixpkgs-architecture/team-log/commit/1177693e973b160dce2ea2cb8a21f6a38f10f375
> Nixpkgs Architecture Team: Add @phaer and @DavHau

- community/teams/nixcon.tt
I need a break from this for now...
> Update NixCon Team

- index.tt
Reverts NixOS/nixos-homepage#1118
NixCon is done!
> Revert "index: add NixCon link to livestream"

- community/teams/moderation.tt
> Domen has stepped down from the moderation team

- .github/workflows/ci.yml
This fixes CI on `main` branch.
ref #1125
> Fix CI on main branch

- community/teams/documentation.tt
This PR is not ready to be merged yet.
Made in cooperation with @infinisil at the latest docteam meeting - and these meeting notes were the basis for it.
https://discourse.nixos.org/t/2023-10-19-documentation-team-meeting-notes-87/34349
I will create this PR as a draft, ask for a 4 eye review and tag all involved users so that they get a chance to confirm or make changes.
> Docteam membership update

- flake.lock
- flake.nix
> remove dependency on nix.dev

- community/teams/moderation.tt
- piegames joined (https://discourse.nixos.org/t/welcome-piegames-to-the-moderation-team/35469)
- Alyssa is leaving
- grahamc is leaving
> Update moderation team

- community/teams/foundation-board.tt
this does not change the semantics of the text, and should ease
making and following future updates.
> fix language errors, formatting, and discourse handles

- community/index.tt
for reference/context: https://invent.kde.org/network/tokodon/-/merge_requests/441
> Add ap/tokodon tag link to community

- community/teams/documentation.tt
Asked to be removed from the team due to time constraints, thanks for all the contributions!
> docs team: Remove @zmitchell

- site-styles/pages/community.less
Follow-up to #1182. This is still not *quite* right, but it's a pretty big improvement. (Sorry, not very good at CSS.)
> Fix positioning of social links

- community/teams/documentation.tt
> as mentioned on chat removing roberth

- README.md
> non automatic refresh instructions with Docker in README.

- community/teams/security.tt
You can verify that the PGP key is tied with my GH account and that I own it on: https://gist.github.com/LeSuisse/5ed34878a0e78194d61a21191b26c4c5
cc @mweinelt
> security team: add myself

- community/index.tt
This was effective for at least 2 months if I remember well.
> Add "Ryan Lahfa" as a board observer

- community/teams/rfc-steering-committee.tt
See https://discourse.nixos.org/t/rfc-steering-committee-rotation-2023-24/36197/13?u=infinisil
Ping @GetPsyched @jonringer @Mmesch
> Update the steering committee

- community/teams/foundation-board.tt
This proposal was prompted by @MMesch, who brought it up at the [NixCon governance workshop](https://discourse.nixos.org/t/nixcon-governance-workshop/32705/6#line-between-community-and-companies-2) and also gave [a talk on the subject at the 23.11 ZHF workshop](https://discourse.nixos.org/t/zurich-23-11-zhf-hackathon-and-ux-workshop-report/37848#lightning-talks-3), and I agree this should be made explicit.
Asking @nixos/foundation to consider for inclusion/clarification of their responsibilities.
> foundation board: address needs of different user types

- community/teams/marketing.tt
add myself to the marketing team
> add avocadoom / thilobillerbeck to marketing

- src/components/ui/Tag.astro
Fix inivisible tags in /community pages foundation board section
> Astro / fix inivisible tags

- src/content/teams/03_security.mdx
- src/pages/community/teams/[...slug].astro
and also ajust the Members box in different resolutions
> Add links to security team GPG Fingerprint

- src/content/teams/03_security.mdx
- src/pages/community/teams/[...slug].astro
> Add tgerbet to security team page

- src/layouts/Header.astro
> Hamburger menu fallback for no-js and fixed menu toggle for keyboard navigation

- src/lib/utils.js
> Prepend posts with their release year

- package.json
> fix: Enable flakes and nix-command extra-experimental-features in Nix

- src/content/teams/10_nix.mdx
- src/styles/base.css
> Added links at the bottom of Nix Team's page

- src/styles/base.css
> Fixed missing `article ol` styles

- src/components/ui/Banner.astro
- src/pages/community.astro
> Add Banner component which is clickable over whole container element

- src/styles/base.css
> Make undeline a bit ticker

- src/pages/community.astro
> Foundation members list is now centered on mobile

- src/components/ui/Asciinema.astro
- src/pages/index.astro
> Use smaller font on Asciinema demos

- src/components/ui/Button.astro
> Use width:auto on small buttons

- src/content/download/50-nixos-isoimage.mdx
- src/content/download/51-nixos-virtualbox.mdx
- src/content/download/99-nixos-more.mdx
Was forgotten about in the astro switch..
Reported by @JulienMalka [on Matrix](https://matrix.to/#/!aGqRytqbCECitOFhbt:nixos.org/$aOm1AMaxASgBBr4j0z7H5Vu_1T9t8W_U0mNV-Bd0vMI?via=nixos.org&via=matrix.org&via=helsinki-systems.de) and @infernoid [on Discourse](https://discourse.nixos.org/t/nixos-download-out-dated-version/41399).
> Update 23.05 -> 23.11 again

- src/content/teams/08_moderation.mdx
This apparently got lost in the migration.
> Update moderation team members

- src/layouts/Layout.astro
I forgot to patch the site title :)
> layout: Replace reproducible with declarative

- src/pages/community.astro
> bring back anchor to teams section

- src/content/teams/11_documentation.mdx
Self-nominated in last meeting: https://discourse.nixos.org/t/2024-03-14-documentation-team-meeting-notes-113/41462
Approved in the docs team private Matrix room
Ping @hsjobeki, let me know if this entry looks good to you!
> docs team: Add hsjobeki

- .github/dependabot.yml
- package-lock.json
- add groups for both github-actions and npm dependencies
- update npm dependencies
> Add dependabot for npm dependencies

- src/components/pages/download/DownloadAccordion.astro
Closes #1115 
Uses `navigator.userAgent` to find user's platform and sets the initial active tab accordingly.
> Download page: open the OS specific tab on page load

- public/demos/cover.scenario
- public/demos/example_3.scenario
- public/demos/example_4.scenario
- public/demos/example_5.scenario
- public/demos/example_6.scenario
- shell.nix
- src/pages/guides/how-nix-works.mdx
This should cause soon-to-be Nix users to see well-formatted code from the beginning :)
> Adapt visible nix to RFC-166

- src/content/teams/04_infrastructure.mdx
Related to https://github.com/NixOS/infra/pull/406
> Update infra team membership, contact, issue link

- flake.nix
- public/demos/cover.scenario
Explain the important parts of the snippets instead of letting the user - possibly new to nix - try
to figure out what they do.
The update in the `flake.nix` file is because I didn't understand at first that the `npm install` was actually required to run `nix run dev`.
> Explain what each code scenario snippet do

- src/content/teams/08_moderation.mdx
I don't have enough time to keep on top of my moderation tasks, so I'm stepping down from the team.
> remove ryantm from moderation team

- src/content/teams/01_foundation-board.mdx
This syncs it with https://github.com/NixOS/foundation.
> Update the foundation board page

- src/content/teams/05_nixos-release.mdx
https://github.com/NixOS/nixpkgs/issues/303285#issuecomment-2080409139
> Update NixOS release team members

- src/content/teams/08_moderation.mdx
> Remove rhendric from moderation team

- src/content/teams/04_infrastructure.mdx
Probably worth making this official :sweat_smile:
> Add edef to the infrastructure team page

- public/netlify.toml
follow-up on #1446, which had a severe blooper, sorry!
> redirect Nix manual URLs to the corresponding relases

- src/content/blog/announcements/2024-05-31_nixos-24.05.md
https://github.com/NixOS/nixpkgs/pull/316026#discussion_r1622966424
> blog: update info on gnome 46

- src/components/pages/community/OfficialCommunityLink.astro
- src/pages/community.astro
This PR
- separates the official community spaces and social media channels
- adds more descriptive texts to the sections that explain their purpose in more detail
> [Community] Separate spaces and social media channels

- src/pages/community.astro
Fix small typo I found while browsing the site.
> Update community page typo

- src/content/teams/04_infrastructure.mdx
He left the infra team a while ago.
https://github.com/NixOS/infra/commit/73e715314b1e07d787e4730cf37f247f582e9601
> Remove delroth from infra team

- src/content/teams/03_security.mdx
See also https://github.com/NixOS/nixpkgs/pull/321519
> teams/security: remove lheckemann

- src/content/teams/03_security.mdx
> teams/security: remove Linus's contact data

- public/netlify.toml
sorry everyone, this mess is currently not getting better as quickly as it should be.
> fix yet another typo in the redirects

- src/content/blog/newsletters/2018_03-a-tree-with-strong-roots.md
Replace unofficial wiki links with official wiki links
> update wiki links

- src/content/teams/10_nix.mdx
Just left the team, so let's reflect that on the website :cry:
> nix-team: Remove thufschmitt

- src/content/teams/07_marketing.mdx
@garbas recently set up StreamYard and said we should get more maintainers and contributors to use it
related: https://github.com/NixOS/nixos-homepage/issues/1479
> marketing: add offer to help with outreach

- src/content/teams/07_marketing.mdx
@garbas this is in preparation for adding notes on using StreamYard
> marketing: remove outdated plans

- src/content/teams/13_geospatial.mdx
If you are already existing Geospatial Team [member](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix), please let us know if you want/don't want your name to appear in the members list. If you are interested in geospatial software and you are not a team member, please consider joining the team. Thank you !
> Add Geospatial team community page

- public/images/teams/geospatial.svg
- src/content/teams/13_geospatial.mdx
* add team logo
* update team description
* alphabetically reorder team members list
> community: update Geospatial team page

- src/assets/image/landing/features/reproducable.svg
> Features: reproducible center the right flake a bit more.

- src/content/teams/08_moderation.mdx
See
https://discourse.nixos.org/t/welcome-picnoir-to-the-moderation-team/50042
> Moderation team: add picnoir

- src/pages/community.astro
> community: add YouTube channel link

- src/content/learning-manuals/02-nixpkgs-manual.mdx
Links to all other languages at the end of the list of languages
> learn: link to list of all languages

- src/content/teams/09_cuda.mdx
Update the website to reflect that I left Tweag/they're no longer sponsoring my CUDA work.
> teams/cuda: update Connor's contact information

- src/content/blog/announcements/2024-09-16_sc-election-2024.md
:rocket:
Ping @thilobillerbeck
> SC Election 2024 announcement

- src/content/blog/announcements/2024-11-05_sc-election-2024-result.md
Follow-up on #1546 :rocket: 
Ping @thilobillerbeck
> Steering Committee election result announcement

- src/content/teams/14_xen.mdx
https://github.com/NixOS/nixpkgs/pull/356074
> teams/xen: remove maintainer; add link to upstream

- src/components/Footer.astro
- src/components/Header.astro
- src/components/util/Link.astro
- src/content/menus/footer.yaml
- src/layouts/Layout.astro
- src/layouts/MDXLayout.astro
- tailwind.config.cjs
- file path for inlineSvg plugin.
- Link component.
- twitter to X icon and URL for footer;
- moved header & footer to components folder (logically these are not layouts);
- small styles improvements.
> Small refactoring

- src/content/teams/08_moderation.mdx
https://discourse.nixos.org/t/leaving-the-moderation-team/58068?u=hexa
> teams/moderation: remove hexa

- src/content/teams/08_moderation.mdx
- nim65s is now a global moderator.
- dan joined the team.
> moderation team: update team list

- src/content/teams/08_moderation.mdx
> moderation: drop danielle

- src/content/blog/announcements/2022-02-23-summer-of-nix-2021-report.md
This post was meant to be posted on 2022-02-23 and not in 2021.
> fix: fix typo on the date of SoN 2021 report post

- src/content/teams/04_infrastructure.mdx
As is the case since several months
> Remove Julien from infra team

- src/content/community/commercial-support.yaml
Closes: #1658 
Content change to point to new link https://www.cyberus-technology.de/en/services
> fix commercial-support link for cyberus-technology

- src/content/teams/15_ngi.mdx
add links to NGI team page as mentioned in #1647
closes #1647
> add links to ngi team page

- src/pages/index.astro
Updated according to https://search.nixos.org/
> Update packages count

- src/content/teams/10_nix.mdx
stepping aside as a Nix maintainer:
https://discourse.nixos.org/t/time-to-step-aside/61050
> remove fricklerhandwerk from Nix team

- src/content/teams/12_formatting.mdx
As agreed upon in todays meeting (notes to be posted), welcome!
> Add new formatting team members

- src/content/teams/01_foundation-board.mdx
See announcement: https://discourse.nixos.org/t/announcing-the-new-nixos-foundation-board/61154
> Foundation: update board

- src/content/teams/11_documentation.mdx
@henrik-ch @yukiisbored @proofconstruction @danielsidhion @djacu just scream-testing due to long inactiviy. Feel free to :-1: or add a suggestion that puts you back in if you're still around.
> update documentation team membership

- src/content/explore/info.yaml
Current text:
> You will no longer have to hear:, **But it works on my machine!**
New text:
> You will no longer have to hear: **But it works on my machine!**
> Delete stray comma on Explore page

- src/content/blog/announcements/foundation-board-2025.md
added the note about the Foundation Board announced on the 4th of March 2025.
> added  Foundation Board 2024 announcement

- src/content/teams/05_nixos-release.mdx
Update for 25.05, see https://discourse.nixos.org/t/25-05-call-for-release-manager-editor/59765/15
> Update NixOS release team members for 25.05

- src/components/pages/community/CommunityPageListItem.astro
- src/pages/community.astro
The project started by Nix has grown into a large and dynamic ecosystem.
We should start maintaining an overview of this ecosystem.
In particular, we should acknowledge the existence of related projects in the functional package management space.
> mention and link alternative implementations

- src/pages/community.astro
as discussed over at https://github.com/NixOS/nixos-homepage/pull/1703
> alternative implementations: incorporate review suggestions

- core/src/components/pages/community/teams/MembersDisplay.astro
- core/src/content/teams/01_foundation-board.mdx
These were internally confirmed by the @NixOS/foundation board members a week ago.
Closes https://github.com/NixOS/foundation/issues/197
> Disclose board member affiliations

- core/src/content/blog/announcements/2025-04-28_nixos-logo-branding-updates/index.md
The date was updated to reflect when the post went live. Added additional commentary to the end.
Added author to the end.
> blog: update branding work announcement

- core/src/content/teams/07_marketing.mdx
Adds Brand and Design Steward to @djacu's title.
> marketing team: update @djacu's title

- core/src/content/teams/12_formatting.mdx
As discussed and agreed-upon in todays formatting team meeting (notes will posted later)
Thanks a lot for stepping up, you'll without a doubt do a great job leading the team, @jfly! :heart:
> Make Jeremy team lead of the formatting team

- core/src/content/download/01-nix-linux.mdx
- core/src/content/download/02-nix-macos.mdx
- core/src/content/download/03-nix-wsl2.mdx
> Make install command more secure

- core/src/content/teams/04_infrastructure.mdx
> Add Arian van Putten to the infra team

- core/src/content/community/commercial-support.yaml
readers coming from this context won't need an introduction to Nix
> link to Tweag service offer directly

- core/src/lib/links.js
> fix link to latest Nix release notes

- README.md
- core/src/pages/community/commercial-support.astro
I replaced the broken link and badge with a new one.
For fixing grammar errors, I used Grammarly primarily and Claude 4 Sonnet for words that I thought Grammarly was wrong.
I can undo the change that fixes grammar if you ask me to do it.
> fix broken links and badge, grammar error

- core/src/content/teams/08_moderation.mdx
See https://discourse.nixos.org/t/welcome-0x4a6f-and-arianvp-to-the-moderation-team/66986
> Moderation page: add 0x4A6F and arianvp

- core/src/pages/donate.astro
Donating should require minimal effort.  
This PR removes the need to scroll down on the Donate page.  
Presenting the options to donate is the content that is most likely to be useful for someone clicking on 'Donate' in the top menu.
> Lower barrier to donate

- core/src/content/teams/05_nixos-release.mdx
according to https://discourse.nixos.org/t/25-11-call-for-release-manager-editors/68351/6?u=leona
> Add jopejoe1 to release management team

- core/src/content/teams/00_steering-committee.mdx
See https://github.com/NixOS/org/pull/159#discussion_r2365817196
> Add GitHub contact method for SC

- core/src/content/teams/160_ngi.mdx
* Remove Valentin Gagarin
* Add role name for Ivan and Daniel
> teams(ngi): update team members and roles

- core/src/content/teams/080_marketing.mdx
Removing as requested.
Ping @tomberek
> teams.marketing: remove Thomas Bereknyei
